### ISSUE TITLE
Remote arming changing to 'Home fails'

### ISSUE THREAD

**Issue by dbrewood** [node-alarm-dot-com/homebridge-node-alarm-dot-com#101]
**Describe the bug**
When returning home after bring away for an hour or so and choosing the 'Home' option, the arming state does not change. 

**To Reproduce**

Launch the 'Home' app on the iPhone
Select the 'Home' control
Tap on 'Home'

**Expected behavior**
The Alarm to unset

**Screenshots**
None needed

**ADC-SystemStates.json**
I can't work out how to get  the debug log off my NAS.

**Homebridge System (v3.0.9):**
* **Node.js Version**: 12.22.7-2029
* **NPM Version**: 1.8.0
* **Homebridge Version**: <1.5.0>
* **Operating System**: Synology NAS (no docker) DSM 7.1.1-42962
* **Process Supervisor**: none

**Additional context**
Config is:

{
    "name": "ADT Security System",
    "username": "my-user",
    "password": "m-pass,
    "logLevel": 4,
    "armingModes": {
        "away": {
            "noEntryDelay": false,
            "silentArming": false,
            "nightArming": false
        },
        "night": {
            "noEntryDelay": false,
            "silentArming": false,
            "nightArming": false
        },
        "stay": {
            "noEntryDelay": false,
            "silentArming": false,
            "nightArming": false
        }
    },
    "platform": "Alarmdotcom"
}

Typical errors are:

[9/11/2022, 10:40:18 AM] [ADT Security System] Error: Failed to change partition state: Error: POST https://www.alarm.com/web/api/devices/partitions/103660714-127/armStay failed: 423
    at post (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:489:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at authenticatedPost (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:433:17)
    at ADCPlatform.changePartitionState (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:590:5)

[9/11/2022, 10:40:29 AM] [ADT Security System] Error: Failed to change partition state: Error: POST https://www.alarm.com/web/api/devices/partitions/103660714-127/armStay failed: 423
    at post (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:489:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at authenticatedPost (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:433:17)
    at ADCPlatform.changePartitionState (/volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:590:5)

**Comment by chase9** [comment]
In the past, a 423 error was associated with sending a comment to your equipment which isn't appropriate. Our example was sending dimmer commands to a regular light switch. Can you verify which arming options your partition is compatible with in your alarm.com app?

**Comment by dbrewood** [comment]
Thanks for the swift reply. In the app we have four Scenes which link in as follows:

Home -> DISARM Home
Away -> ARM (AWAY HOME / Active Sensors (Dining Room Motion Activated & Living Room Motion Activated)
Sleep -> ARM (STAY) Home /  Active Sensors (Dining Room Motion Activated & Living Room Motion Activated)
Wake Up -> DISARM Home

Is that what you need?

**Comment by chase9** [comment]
I’m wondering if you see any arm/disarm options in the app. For example, this is what I see when I attempt to disarm my panel:



Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by dbrewood** [comment]
Yes, I see as follows for each mode:
![Union_Scenes](https://user-images.githubusercontent.com/93347139/189539215-6a1276f5-ee91-4188-95a8-f7e7db5b007f.jpg)

**Comment by ngori** [comment]
Hi @dbrewood 

It appears you are using ADC scenes here but I'm not sure you need to. I also use them as well but not with the homebridge plug-in. For example I have our ADC sleep scene to lock all doors, close our garage door, turn off all lights and set the alarm to home stay. I believe the plug-in only supports changing the arm state the first command in your scenes within HomeKit (what you are seeing in Chase's screenshot). I ended up recreating my ADC scenes within HomeKit directly so I didn't need to use the ADC app. 

> Yes, I see as follows for each mode:
> 
> ![Union_Scenes](https://user-images.githubusercontent.com/93347139/189539215-6a1276f5-ee91-4188-95a8-f7e7db5b007f.jpg)
> 
>

**Comment by dbrewood** [comment]
Okay I think I'm with you. So how would I go about using HomeKit to set the scenes in the ADT / alarm.com system?? 
Basically we just want to duplicate the scenes above with one control (or multiple controls if we have to) so we can then replace the ADT as much as possible (apart from the SkyBell).
I had thought this plug in was designed to do that as standard? Excuse my ignorance i've only been using Homebridge for 3 days :)

**Comment by ngori** [comment]
So I don't typically change my arm state directly with the Home App. 

That would look like this ![image](https://user-images.githubusercontent.com/29135202/189544563-b84f78b3-3e7d-447c-8e58-0cfbc60038ba.png)

These would align to the arm/disarm options Chase showed. 

My locks and garage door are controlled/managed by my panel/ADC (they are zwave devices and the panel is the zwave controller). This plug-in exposes those devices in HomeKit as separate accessories so I can lock a door or open/close the garage. 

I use scenes setup in HomeKit (think running a macro). This is part of my good night scene. Doors locked, garage down, lights off, alarm set to home stay (no motion sensors). 

![image](https://user-images.githubusercontent.com/29135202/189544687-04859517-6ff7-4d3d-9d00-38d598bb7035.png)

The distinct here is scenes controlling multiple devices vs arming options. I don't use any specialized arming options (silent, delayed, etc) so I can't speak to those. I also don't have ADT as my provider so I'm not sure if their service has nuances from a more vanilla ADC provider like I use. 

> Okay I think I'm with you. So how would I go about using HomeKit to set the scenes in the ADT / alarm.com system?? 
> 
> Basically we just want to duplicate the scenes above with one control (or multiple controls if we have to) so we can then replace the ADT as much as possible (apart from the SkyBell).
> 
> I had thought this plug in was designed to do that as standard? Excuse my ignorance i've only been using Homebridge for 3 days :)
> 
> Was my configuration in error above? It did seem that:
> 
> 
> 
> "night": {
> 
> "noEntryDelay": false,
> 
> "silentArming": false,
> 
> "nightArming": false
> 
> },
> 
> 
> 
> Was wrong as it was a night set but night arming was set to false?
> 
>

**Comment by dbrewood** [comment]
Right I understand what you are doing...... My other half alas does not like complex night scenarios etc.  All we want to do it to be able to arm / disarm / change arm modes etc with the Home app instead of using the ADT app.
Any ideas what we need to change?

**Comment by ngori** [comment]
Got it. Yea that's odd. I have the exact same config in homebridge. When I toggle alarm state using the alarm accessory in the home app. I'm able to effectively set the alarm to any of the 3 states from the panel: arm away, arm stay, disarm. I don't personally use night arming ever. 

Do you always use the scenes in the ADC app or do you ever change the "security system" status directly?

![image](https://user-images.githubusercontent.com/29135202/189793860-ae801950-084c-43a3-a423-822c617c77a8.png)

**Comment by dbrewood** [comment]
Hmm strange we're getting differences in operation. It is actually working great 99% of the time. The only issue is when we've been away from the house 'Away' and then we return and disarm using 'Home', so that'd be:

Away -> ARM (AWAY HOME / Active Sensors (Dining Room Motion Activated & Living Room Motion Activated)

When leaving the house and

Home -> DISARM Home

When we get home. Or should I be using 'Off' when we get home?

**Comment by ngori** [comment]
OFF is the Home App equivalent disarmed for ADC.  Give that a try next time. 

HOME is the equivalent of armed stay for me with the default config.

**Comment by dbrewood** [comment]
Right but would not OFF disarm and turn off the sensors? Whereas HOME sounds like it would be the same as SLEEP for me?
Whereas in the iOS App I have:

Home -> DISARM Home
Sleep -> ARM (STAY) Home / Active Sensors (Dining Room Motion Activated & Living Room Motion Activated)

So for me HOME should be DISARM Home and not ARM (STAY) Home?

**Comment by chase9** [comment]
If you are still needing help on this, please open a new issue.
