### ISSUE TITLE
SkyBell?

### ISSUE THREAD

**Issue by dbrewood** [node-alarm-dot-com/homebridge-node-alarm-dot-com#102]
Our ADT System which uses alarmdotcom includes a SkyBell video doorbell...... Is there any chance in the future that this could be incorporated into the node plugin?

I know there was a SkyBell plugin but it was discontinued and is out of support / no longer available?

**Comment by chase9** [comment]
Nothing is out of the question, but since I don't have one myself it will be at the back of the backlog. PRs are always welcome if someone if willing to contribute the code :smile:
