### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#103]
Started  a few days ago.   1.18.0.  Working beautifully for months and all of a sudden

SystemERRORloginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo EAI_AGAIN www.alarm.com

alarm.com app works fine. There has been no changes to my config.

**Comment by scottleestrange** [comment]
0/1/2022, 5:49:50 PMWARNINGplugin site unavailable
10/1/2022, 5:50:11 PMNode Alarm Dot Com BridgeSecurity SystemLogging into Alarm.com as strange4358
10/1/2022, 5:50:11 PMNode Alarm Dot Com BridgeSecurity SystemERRORloginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo EAI_AGAIN www.alarm.com
10/1/2022, 5:50:11 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:50:11 PMNode Alarm Dot Com BridgeSecurity SystemERRORrefreshDevices Error: Cannot read properties of undefined (reading 'map')
10/1/2022, 5:50:11 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:51:16 PMNode Alarm Dot Com BridgeSecurity SystemLogging into Alarm.com as strange4358
10/1/2022, 5:51:16 PMNode Alarm Dot Com BridgeSecurity SystemERRORloginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo EAI_AGAIN www.alarm.com
10/1/2022, 5:51:16 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:51:16 PMNode Alarm Dot Com BridgeSecurity SystemERRORrefreshDevices Error: Cannot read properties of undefined (reading 'map')
10/1/2022, 5:51:16 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:52:18 PMNode Alarm Dot Com BridgeSecurity SystemLogging into Alarm.com as strange4358
10/1/2022, 5:52:18 PMNode Alarm Dot Com BridgeSecurity SystemERRORloginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo EAI_AGAIN www.alarm.com
10/1/2022, 5:52:18 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:52:18 PMNode Alarm Dot Com BridgeSecurity SystemERRORrefreshDevices Error: Cannot read properties of undefined (reading 'map')
10/1/2022, 5:52:18 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.
10/1/2022, 5:53:02 PMWARNINGplugin site unavailable
10/1/2022, 5:53:02 PMWARNINGplugin site unavailable
10/1/2022, 5:53:04 PMWARNINGplugin site unavailable
10/1/2022, 5:53:04 PMWARNINGplugin site unavailable
10/1/2022, 5:53:04 PMWARNINGplugin site unavailable
10/1/2022, 5:53:04 PMWARNINGplugin site unavailable
10/1/2022, 5:53:04 PMWARNINGplugin site unavailable
10/1/2022, 5:53:11 PMWARNINGplugin site unavailable
10/1/2022, 5:53:11 PMWARNINGplugin site unavailable
10/1/2022, 5:53:11 PMWARNINGplugin site unavailable
10/1/2022, 5:53:11 PMWARNINGplugin site unavailable
10/1/2022, 5:53:11 PMWARNINGplugin site unavailable
10/1/2022, 5:53:13 PMWARNINGplugin site unavailable

**Comment by scottleestrange** [comment]
I found the issue.  Please close.  Somehow both my joins boxes lost their dns settings.  Bad name server

**Comment by chase9** [comment]
Just to be clear for anyone in the future, the error `plugin site unavailable` is related to you having some sort of device on your network which wasn't able to communicate out to the internet properly?
