### ISSUE TITLE
Arming State No Longer Triggers Automations

### ISSUE THREAD

**Issue by danglez83** [node-alarm-dot-com/homebridge-node-alarm-dot-com#104]
Up until a couple of weeks ago, my automations that were setup based on arming state, were working flawlessly. Now, they never trigger the automations. Arming/disarming works in HomeKit and the state is accurate, as is the state notification, but no longer triggers automation. If I manually test the automation, it works as expected.

**Comment by chase9** [comment]
Seems to be an issue with iOS 16 :https://www.reddit.com/r/HomeKit/comments/y3gult/automations_arent_firing/

Are you on iOS 16?

**Comment by chase9** [comment]
Closing with no response
