### ISSUE TITLE
Not fully showing in HK

### ISSUE THREAD

**Issue by hasrt1206** [node-alarm-dot-com/homebridge-node-alarm-dot-com#119]
**Describe the bug**
<I am not able to see my "Security Panel". I am able to add it to homekit, it shows the hub but not the panel itself.>

**To Reproduce**
N/A

**Expected behavior**
<To see my device in HomeKit>

**Screenshots**
<N/A>

**Comment by chase9** [comment]
Are you able to use homebridge-ui-x and see if the panel shows up there?

**Comment by hasrt1206** [comment]
I was not able to see it on the Homebridge interface. I think the problem was that I was not able to login to Alarm.com having 2FA. What I did was set up a separate account with minimal access for it to log into the web services for Alarm.com

**Comment by chase9** [comment]
Awesome, glad you got it working. Long term I would recommend enabling proper MFA for better security but also because they seem to be transparently forcing users onto MFA.

https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/wiki/Two-Factor-Authentication-Support
