### ISSUE TITLE
Night arming causes error since last updated

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#135]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**ADC-SystemStates.json**

**Homebridge System (please complete the following information):**
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Additional context**

**Comment by scottleestrange** [comment]
My guess is your last update to night arming broke some users like me. I will upload logs tomorrow

**Comment by chase9** [comment]
Would you be able to upload your logs? I need more information to dive into this.

**Comment by chase9** [comment]
Hey @scottleestrange just a quick ping if you have the time to post your logs! The fix for night arming that was introduced was actually fixing a typo which would have made it so night arming never worked. I'm wondering if the fix for you would be to disable that option from your config?

**Comment by scottleestrange** [comment]
I sent the logs

Yes, disabling Night does bypass the issue

**Comment by chase9** [comment]
I'm not seeing any logs on my end... In any case, it sounds like we found the issue. I'm not sure if there is anything we could do to fix it besides possibly putting a warning in the logs when these settings are enabled and an arm call fails. What do you think about that?

**Comment by scottleestrange** [comment]
Could be, let me call the alarm company and ask about my configuration and if night arming is there

**Comment by chase9** [comment]
Going to close this one, ping me if you found out it's not an issue with the options you're sending.
