### ISSUE TITLE
Constant reinstallation of accessories in HomeKit

### ISSUE THREAD

**Issue by psantia01** [node-alarm-dot-com/homebridge-node-alarm-dot-com#136]
**Describe the bug**
I've loaded the plugin Homebridge Node Alarm dot com which is verified.  All the accessories are in Homebridge and I can control lights, etc.  However, in HomeKit, it's constantly losing the connection for all the added accessories in HomeKit.  It seems the only way I can reconnect to them is to deinstall the bridge and then adding it back into HomeKit...causing me to go through adding each accessory all over again.  This is extremely annoying.  But the issue keeps coming back even after I've done that.  I check the logs in Homebridge and nothing is telling me there are issues.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/4534a1d8-af7d-478d-a256-e4a169bcd436)
  all the No response is from Alarm.com

**ADC-SystemStates.json**
I don't have this sorry.

**Homebridge System (please complete the following information):**
* **Node.js Version**: 20.18.0
* **NPM Version**: I don't know where to find this.
* **Homebridge Version**: 1.8.4
* **Operating System**: Raspbian 
* **Process Supervisor**: Homebridge Supervisor (I believe)

**Additional context**
I've also tried to restart HomeKit.  When I do, for Alarm.com, it tries to get an update, but then returns No response once again.

**Comment by psantia01** [comment]
I noticed that when the child restarts, it loses connection.  Not sure how to get it to reconnect without uninstalling the bridge and then starting over.

**Comment by chase9** [comment]
Can you increase your logging level for the plugin to debug and then send me your logs? It sounds like you might be running into an error which is crashing the child bridge.

**Comment by chase9** [comment]
Closing this issue since I didn't hear back. This sounds like an issue with the network instead of the plugin to me. If you're still having issues, you should try making sure that your server's firewall is setup properly, and try playing around with the mDNS advertiser.
