### ISSUE TITLE
Implement support for more devices

### ISSUE THREAD

**Issue by chase9** [node-alarm-dot-com/homebridge-node-alarm-dot-com#18]
I'm creating this issue to track progress on adding support for lights, garage doors, thermostats, and locks.

- [x] Lights
- [x] Locks
- [x] Garage Doors
- [x] Thermostats

## Notes
*Note: I have no idea what statePollOnly is, but I assume it's for only returning the current status of a device.*

> **Mike Kormendy:**<br>statePollOnly is used for telling their API whether or not you want to poll for the state after it has been set. In most cases, we don't need to poll for the state after we set it because we are keeping our own state status in our code. However, I believe their system may be event driven and need to refresh itself based on state controlled by their API and not internally in their clients.

### Lights
The endpoint for lighting control is `https://www.alarm.com/web/api/devices/lights/<device id>/<turnOn, turnOff>`. This is a POST request with the body `{"dimmerLevel":<1-100>,"statePollOnly":false}`. This body is used with both the turnOff and turnOn endpoints.

### Locks
The endpoint for locks is `https://www.alarm.com/web/api/devices/locks/<device id>/<unlock,lock>`. The body of the request is `{"statePollOnly":false}`.

### Thermostats
Thermostats have a lot of configurable settings, including temperature, fan, cooling setpoint, heating setpoint, and mode. I only grabbed the information for mode and setpoint since they're tied together and I believe it's the only control implemented in homekit.

The endpoint for setting thermostats is `https://www.alarm.com/web/api/devices/thermostats/<device id>/setState`. The potential body of the request is `{"desiredState":x,"desiredHeatSetpoint":59,"desiredCoolSetpoint":86,"statePollOnly":false}`.

- Desired state can be a number between 1 and 4.
 1. off
 2. heating
 3. cooling
 4. auto
- desiredCool/HeatSetpoint is an integer. I use fahrenheit in my example.

I'm unfamiliar with the project but will try my best at adding these features in a PR!

**Comment by ngori** [comment]
I started some work on PR focused on garage doors and locks for my home.
 Then life and a baby happened and it got put on the back burner

For Garage Doors the endpoint is
https://www.alarm.com/web/api/devices/garageDoors/<device id>/<open,close>

I have everything in my alarm.com setup (lights, locks, thermostat (heat
only), garage doors) so happy to test if someone doesn't have the devices
in their home.

**Comment by mkormendy** [comment]
Since I can’t test this whatsoever, I’m going to rely on your PRs after significant testing. Please keep me in the loop and let me know if there’s anything I can do to help.

**Comment by chase9** [comment]
@ngori Would you want to push your PR up to github as WIP so we could work together? Otherwise tonight or tomorrow I'll likely start on this myself.

**Comment by chase9** [comment]
I only have one lock to test, but it seems to be working fine. The only problem I wasn't able to solve is that the app will sometimes say "no response" although it actually accurately reflects the lock state. Any ideas?

**Comment by mkormendy** [comment]
@chase9 re: the "no response" - I've seen that with a number of other non-alarm.com related devices as well. I have that happen with my LiftMaster myQ garage door (HomeKit certified).
Tough to nail down what is causing it, and it happens with homebridge related devices more frequently too.

**Comment by mkormendy** [comment]
@chase9 which compatible lock are you using for Alarm.com? I may just get my installer to install one to test this out.

**Comment by chase9** [comment]
It seems like the problem goes away when calling `callback()` earlier. Perhaps Siri times out when it has to wait for Alarm.com to respond?

As for what lock I'm using, I unfortunately don't know the exact model. I can check when I get home, but I know off the top of my head it's a Kwikset deadbolt with a 10-key keypad and a lock button.

I was looking at the forks for node-alarm-dot-com and noticed this branch already contains some support for other devices: https://github.com/fjiang423/node-alarm-dot-com/commit/51d32d3277cc3bf482419ffdff244c307a13abbd. This should speed up the development process!

**Comment by mkormendy** [comment]
Interesting! I have left a message to find out the status of that fork. I may pull it back in if it's working.

**Comment by chase9** [comment]
Is the configureAccessory method orphaned code? I'm unable to find references to it within homebridge-node-alarm-dot-com.

**Comment by chase9** [comment]
I've added support for lights with dimmers as this is all I have. However, I noticed that alarm.com has support for a wider variety of lighting, so I'm not sure how well this will work with other types of lights (notably lights without dimmers).

If anyone has experience with creating a global timer, I could use the help. When using the home app commands are sent to your lights as you drag along, but alarm.com prefers only one update is sent for a light. While this implementation works, I think it might be better if we wait x seconds after the last command was sent from homebridge before sending a command to alarm.com.

**Comment by mkormendy** [comment]
> Is the configureAccessory method orphaned code? I'm unable to find references to it within homebridge-node-alarm-dot-com.

I came across that too, and it could possibly be. Have you tested removing it and seeing if things still work? I haven't been in the module much lately, but I can look at it this weekend.

**Comment by chase9** [comment]
Hi @mkormendy, I've been testing lights and locks for the past few days and haven't run into any problems. I've started working on thermostat support but the extra complexity means there's more to do. I think I'm ready to merge lights and locks so that people can get their hands on it, and I will create separate requests for thermostats and eventually garage doors.

What do you think?

**Comment by mkormendy** [comment]
> Hi @mkormendy, I've been testing lights and locks for the past few days and haven't run into any problems. I've started working on thermostat support but the extra complexity means there's more to do. I think I'm ready to merge lights and locks so that people can get their hands on it, and I will create separate requests for thermostats and eventually garage doors.
> 
> What do you think?

Sounds good! Do you feel your PR is ready for review?

**Comment by chase9** [comment]
I believe so! I just reverted the LOG_LEVEL to 3, and with that I believe the code is ready. Like I said, I haven't run into any problems with my own setup so I'm not sure what more I could test! I do think this issue should stay open to track what progress I eventually make on thermostats and garage doors though.

**Comment by mkormendy** [comment]
One last question, did you figure out the Dimmer portion? You were asking if anyone had created a "global timer". I haven't looked at your code, but Is that still an issue or did you figure it out?

**Comment by chase9** [comment]
The issue with the dimmer was that as you slide around, Siri will send multiple updates to the API. As those updates call back, the home app can appear to jump around before landing on the final brightness.

This was solved by moving the callback outside of the Ajax call to the Alarm.com API. Admittedly this is a bit of a workaround as Siri will say your light is in a different state than reality for a few seconds, but I believe this smoothness to be more preferable to the slider jumping around!

**Comment by mkormendy** [comment]
What I would like to do is get @ngori to QA your fork first, since I have no way of testing this. @ngori would you mind testing @chase9's fork with your setup?

**Comment by ngori** [comment]
Sure.  I should be able to test this weekend.  I did realize my the light I
have connected to my panel is an on/off not a dimmer so my test there will
be limited a bit (I mainly use it as a z-wave extender).   But I can
definitely test the lock setup.

**Comment by mkormendy** [comment]
Thanks guys, really appreciate the help here. I was going to get my LiftMaster garage door hooked up to our Alarm.com account to test that portion, but I haven't heard back from our installer for over a week 😢.

**Comment by chase9** [comment]
Hopefully they get back to you soon Mike!

I’m glad that you don’t have a dimmer as I’m interested in seeing how the code responds. Based on the returns from alarm.com I’m hoping it’ll toggle between 100% and 0%. If not perhaps we could build some checks for dinners and change what’s reported to HomeKit.

**Comment by ngori** [comment]
Just got everything installed on my system tonight.  I had to clear the accessory cache to get locks and lights to pull through homebridge.  Our lock is working just fine.  On the light side I should have realized what was going to happen.  We have 1 z-wave module that shows on our panel but we also have a pretty extensive Lutron setup that is cloud to cloud integrated with ADC. Those are present on the ADC web interface.  So the plugin basically duplicated my entire house of lights and scenes in Homekit.   Oh well.   The z-wave lamp module is working as expected 0% for off and 100% for on.   The cloud integrated dimmers work too just with a pretty substantial delay. Nice work Chase!

**Comment by chase9** [comment]
Thank you, I'm glad that it's working :)

If you're comfortable snooping around with your browser developer tools, I wouldn't mind seeing what your lights look like on alarm.com, as well as what API calls they make. If I could get that information, it should be possible to check if lights are dimmers and show them appropriately in homekit.

**Comment by ngori** [comment]
Yea not a problem.  Let me know if there is anything else specific you want
to see.

This is the POST for a dimmable light.  The only difference is for an
on/off only light is "isDimmer: False" and light level remains unchanged at
100 only the desiredState toggles between 2 and 3 to turn it on/off.  I
stripped out my system id here.

The URL is always turnOn for any change in dimmer setting except for
turning it off which is the aptly named turnOff


URL:

   1. Request URL:
   https://www.alarm.com/web/api/devices/lights/XXXXXXX-2204/turnOn



Preview:


   1. {data: {id: "XXXXXXXX-2204", type: "devices/light",…}, included: [],…}
      1. data: {id: "XXXXXXXXXX-2204", type: "devices/light",…}
         1. attributes: {state: 2, desiredState: 2, isDimmer: true,
         isFavorite: false, lightLevel: 62, isZWave: false,…}
            1. batteryLevelNull: null
            2. canBeSaved: true
            3. canChangeDescription: true
            4. canConfirmStateChange: true
            5. canEnableRemoteCommands: true
            6. canEnableStateTracking: false
            7. criticalBattery: false
            8. description: "Sink Light"
            9. desiredState: 2
            10. deviceIcon: {icon: 0}
               1. icon: 0
            11. hasPermissionToChangeState: true
            12. isDimmer: true
            13. isFavorite: false
            14. isZWave: false
            15. lightLevel: 62
            16. lowBattery: false
            17. remoteCommandsEnabled: true
            18. shouldShowFavoritesToggle: true
            19. state: 2
            20. stateTrackingEnabled: true
         2. id: "XXXXXXXX-2204"
         3. relationships: {lightGroups: {data: [], meta: {count: "0"}},
         system: {data: {id: "XXXXXX", type: "systems/system"}},…}
            1. lightGroups: {data: [], meta: {count: "0"}}
               1. data: []
               2. meta: {count: "0"}
                  1. count: "0"
               2. stateInfo: {data: {id: "XXXXXX-2204-3", type:
            "devices/state-info"}}
               1. data: {id: "XXXXXX-2204-3", type: "devices/state-info"}
            3. system: {data: {id: "XXXXXX", type: "systems/system"}}
               1. data: {id: "XXXXXXX", type: "systems/system"}
            4. type: "devices/light"
      2. included: []
      3. meta: {transformer_version: "1.1"}
         1. transformer_version: "1.1"



Response:

{
  "data": {
    "id": "XXXXXXXX-2204",
    "type": "devices/light",
    "attributes": {
      "state": 2,
      "desiredState": 2,
      "isDimmer": true,
      "isFavorite": false,
      "lightLevel": 62,
      "isZWave": false,
      "stateTrackingEnabled": true,
      "shouldShowFavoritesToggle": true,
      "remoteCommandsEnabled": true,
      "canChangeDescription": true,
      "canEnableRemoteCommands": true,
      "canEnableStateTracking": false,
      "canBeSaved": true,
      "description": "Sink Light",
      "canConfirmStateChange": true,
      "hasPermissionToChangeState": true,
      "deviceIcon": {
        "icon": 0
      },
      "batteryLevelNull": null,
      "lowBattery": false,
      "criticalBattery": false
    },
    "relationships": {
      "lightGroups": {
        "data": [],
        "meta": {
          "count": "0"
        }
      },
      "system": {
        "data": {
          "id": "XXXXXXX",
          "type": "systems/system"
        }
      },
      "stateInfo": {
        "data": {
          "id": "XXXXXXXXXX-2204-3",
          "type": "devices/state-info"
        }
      }
    }
  },
  "included": [],
  "meta": {
    "transformer_version": "1.1"
  }
}

**Comment by mkormendy** [comment]
> Thank you, I'm glad that it's working :)
> 
> If you're comfortable snooping around with your browser developer tools, I wouldn't mind seeing what your lights look like on alarm.com, as well as what API calls they make. If I could get that information, it should be possible to check if lights are dimmers and show them appropriately in homekit.

Yeah @chase9 just for a complete lighting feature-set , I think we'd all prefer that the dimmable lights appear with a slider switch and the non-dimmable appear as a on/off state switch in the home app. Let me know if you need help figuring that out.

**Comment by ngori** [comment]
I nearly have my garage door working (got it to open one time tonight).    I just need to clean up some state issues and it should be good.  I can add another pull request for my code once I sort out the last bits hopefully this week.

**Comment by ngori** [comment]
I got my garage door working reliably now.  One small issue is that I get a "No Response" in Home immediately following an open or close command that resolves itself after what I think is the next poll of ADC by the plugin.  I'm pretty sure this can be fixed though as the same issue doesn't appear for locks and the Services/Characteristics are very similar.  I unfortunately/selfishly started the Garage Doors off Chase's pull request so I could have locks and garage doors at our house.  I should be able to submit another pull request with just the garage door commit after Chase's PR has been reviewed and approved if that makes sense with Mike

**Comment by chase9** [comment]
That's great! The no response issue is what I talked about above where I had to cheat a little. I believe it's because siri times out before callback() resolves, so I moved callback() out of the ajax request to alarm.com.

**Comment by chase9** [comment]
Sorry about the delay, I've been pretty busy at work. I just pushed a minor change which should prevent non-dimmable lights as showing up as dimmers.

**Comment by mkormendy** [comment]
Hey @chase9 do non-dimmable lights show up as simply on/off lights with this change?

**Comment by chase9** [comment]
Yes! I don’t have non-dimming lights to test, but with those sections commented out my simmer appeared and worked as just a regular switch. I have to infer this’ll also work for others lights.

**Comment by lwpmoon** [comment]
Pulled your changes and have been testing with a few on/off switches and I’ve not run into any issues. 

> Yes! I don’t have non-dimming lights to test, but with those sections commented out my simmer appeared and worked as just a regular switch. I have to infer this’ll also work for others lights.
> […](#)
> On Nov 17, 2019, at 10:39 AM, Mike Kormendy ***@***.***> wrote: ﻿ Hey @chase9 do non-dimmable lights show up as simply on/off lights with this change? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mkormendy** [comment]
@chase9 I have merged the changes and deployed to the github and npm repo, bumping versions and what-not. Thank you and everyone else for your code and testing for me in my absence of having these devices myself.

> I got my garage door working reliably now. One small issue is that I get a "No Response" in Home immediately following an open or close command that resolves itself after what I think is the next poll of ADC by the plugin. I'm pretty sure this can be fixed though as the same issue doesn't appear for locks and the Services/Characteristics are very similar. I unfortunately/selfishly started the Garage Doors off Chase's pull request so I could have locks and garage doors at our house. I should be able to submit another pull request with just the garage door commit after Chase's PR has been reviewed and approved if that makes sense with Mike

@ngori if you're keen, take the new latest master, fork, and add your garage code in and then submit a pull request. I'll review it and if all's well, I'll merge it in a new release.

**Comment by ngori** [comment]
Sounds good.  I'll take a crack at forking the latest this week/weekend and
adding my code in.

**Comment by mkormendy** [comment]
@ngori There are issues (#23, #24, #25) with the latest release. Before adding your code for the garage, the code needs to be fixed in both the node base module as well.

**Comment by ngori** [comment]
@mkormendy Yes, was about to chime in I'm going to hold off adding the garage code until the error handling gets worked out for locks and lights.   I'm not much help on that front as my ADC account is the tier with all the emPower features enabled (different ADC resellers market the monitoring tiers differently, mine was called Gold Interactive back when I signed up). Hopefully, someone without EmPower enabled can assist on the API calls without the automation features enabled.

**Comment by mkormendy** [comment]
@ngori updated the plugin with error handling. See how that was done, and duplicate with the garage code. Should be pretty straightforward.

**Comment by ngori** [comment]
@mkormendy Been AFK myself for a few weeks for the holidays and vacation.  I'll take a look at the latest version and adding in my garage code when I catch back up at home and work.

**Comment by mkormendy** [comment]
@ngori, I'm working on some code cleanup after taking a step back and looking at it again. I'll be publishing that soon, so no rush on your part if you're swamped with getting back to life.

**Comment by wesbro** [comment]
@mkormendy If you need me to help test the garage let me know. I'd love to have this feature too.

**Comment by mkormendy** [comment]
@wesbro thank you.
@ngori I've made my changes in both repos for this project. Should be cleaner for you to see the pattern of how to add accessories.

**Comment by Paulg5678** [comment]
Hey, dumb question, are the contact sensors for doors/windows being worked on?  I can see them in my home app through this plugin, but they always report closed even when the door or window is open.  I didn't want to report a bug if this feature wasn't fully implemented yet.

**Comment by mkormendy** [comment]
@Paulg5678 it's not fully implemented.

**Comment by Paulg5678** [comment]
Ok, thank you for the info, I'm sorry to bother you with that

**Comment by ngori** [comment]
@Paulg5678 I'm just curious what window/door sensors you are using?  We have Qolsys S-line sensors and I do get updates in the Home App when a door or window is left open.

**Comment by Paulg5678** [comment]
I’m using the hardwired sensors that came with our alarm system. This plugin also apparently is exposing the carbon monoxide detector, motion detector, and fire alarm that our built in guardian protection system came with

**Comment by ngori** [comment]
Ah ok.  We don't have anything hardwired here.  Just curious do you see the sensors report their status on the ADC web interface?  

We have an Encore Firefighter that listens to our smoke/CO2 sensor that shows as a normally closed contact sensor in the Home App as well.  I just add it to the ignored devices list though.  Not a lot of benefit in seeing it the Home App for us.  It throws it's low battery warning on our panel and in the ADC app when it's time to replace the battery.

**Comment by Paulg5678** [comment]
I do see the door and window sensors report the correct status on the alarm dot com website and it’s corresponding app.

**Comment by mkormendy** [comment]
I have just verified that my door contact sensors all work. @Paulg5678 would you mind setting your debug log to a value of 4 and then sending me the JSON payload via a DM to me on the slack channel?

**Comment by Paulg5678** [comment]
I actually just checked on this, and they do report open states, but there's a delay of no less than 30 seconds before the state in home bridge reflects reality.

**Comment by mkormendy** [comment]
@Paulg5678 well that's good news. That's likely due to the latency between the network transfer of the states from the cellular modem on the alarm system to their servers, then from our polling of their Web API servers on your homebridge to the hub (and if you're not on your local network, to the Homekit servers that your Home app connects to).

Sorry bub, I wish there was a way for the alarm system to directly connect to a local wifi network and use something like MQTT or a local websocket to tell homebridge the states of all of the sensors and accessories on the Alarm.com system.

**Comment by andrewfblack** [comment]
Any chance of adding SkyBell doorbell linked to alarm.com to HomeKit?

**Comment by mkormendy** [comment]
> Any chance of adding SkyBell doorbell linked to alarm.com to HomeKit?

Without official developer backing from Alarm.com, and their continuous addition of accessories to broaden their ecosystem  beyond what started out as a simple alarm system, I don't foresee this happening any time in the next year or two.

**Comment by ngori** [comment]
@mkormendy   The SkyBell has an officially supported ADC version of their product (adc-vdb105) that integrates directly with alarm.com.  I briefly looked at it before going with a Nest Hello.  No idea what the api calls look like though.

**Comment by benvblanco** [comment]
Was the garage code successfully tested and added?

**Comment by mkormendy** [comment]
@benvblanco @ngori's pull request is in code review at the moment. No ETA when it will be merged yet.

**Comment by andrewfblack** [comment]
Yeah I have the ADC SkyBell camera on my alarm.com account I wasn’t sure if you would add support for it to this plug in.  I hate to buy a new doorbell camera but I may have to.

**Comment by ngori** [comment]
@andrewfblack Just curious, what would the expected use case be for the doorbell for Homekit?  Just a Home App tile to open up a live look at the doorbell feed?   Doorbell presses pop up as a notification for two way communication, correct?

**Comment by mkormendy** [comment]
@benvblanco the garage code has been tested and added. Pls update and test for yourself. Create a new ticket if there are any issues.

**Comment by Paulg5678** [comment]
Not to bother, but I just updated the plugin and I do not see my garage door in my accessories, is there something that needs to be added to the config on my end?

**Comment by mkormendy** [comment]
@Paulg5678 are you using Config UI X? Did you restart Homebridge itself? Did you try refreshing the accessories cache? (see #28

**Comment by Paulg5678** [comment]
Yes, I am using Config UI X, I refreshed the cached accessories cache, now the garage door shows up.  However, now I'm seeing that after using the home app on my phone or iMac to open or close the garage door (the physical action works) I see 'No Response' on the doors icon, seeing if there's a delay or something like there is with the contact sensors, but its been a good 3 or 4 minutes since I just closed it with the app and its still 'No Response'

**Comment by Paulg5678** [comment]
Ok, so after a good while, the garage door icon finally reported a status in the home app, but it shows 'Open' when the garage door is closed, alarm.com website and app both report closed correctly as well.  If you need me to pull logs, let me know and I will get them this evening.

**Comment by mkormendy** [comment]
Let's bring this into a new ticket. @ngori can you help debug this since you created the implementation?

**Comment by ngori** [comment]
@mkormendy sure thing

**Comment by mkormendy** [comment]
@wesbro we've updated the alarm.com code to include garage doors, can you test your garage door now?

**Comment by derekschinke** [comment]
If thermostats need to be tested, I'm more than happy to help.

**Comment by chase9** [comment]
Thanks Derek. Right now this is on the backburner while we work on making the current implementations more reliable. Of course, I won't stop anyone from submitting a PR!

**Comment by ifeign** [comment]
> @andrewfblack Just curious, what would the expected use case be for the doorbell for Homekit? Just a Home App tile to open up a live look at the doorbell feed? Doorbell presses pop up as a notification for two way communication, correct?

The main reason I want camera integration is simplicity of sharing. I don’t mind having the  alarm.com app on my phone, but being able to share with my wife and guests is so easy with the Home app, they can already access everything else in the security system via this plugin. I’ve used the HomeBridge-ring plugin and I know the Abode plugin also pulls in cameras, so cloud-based cameras are viable with HomeBridge, the question is whether alarm.com lets you pull that information. 

I will gladly test and provide any information needed, I’m about to move into a house that comes with an alarm.com VDB770 doorbell.

**Comment by franklixuefei** [comment]
What’s the status of the thermostats? What about audios?

**Comment by JCallender73** [comment]
Has anyone been able to find a way to integrate the cam feeds into Homebridge?  I've seen lots RTSP feed setup for older ADT camera's but cannot find anything on the newer OC845-ADT.

**Comment by ifeign** [comment]
> 
> 
> Has anyone been able to find a way to integrate the cam feeds into Homebridge? I've seen lots RTSP feed setup for older ADT camera's but cannot find anything on the newer OC845-ADT.

https://github.com/node-alarm-dot-com/node-alarm-dot-com/issues/13

**Comment by atlcoder** [comment]
I have a few devices that are all reporting as contact sensors, however it seems that the plugin could report them as the appropriate devices to HomeKit:

**Device Type: deviceType code**
CO Detector: 6
Smoke Detector: 5
Contact Sensor: 1
Motion Sensor: 2
Glass Break: 19 (as mentioned above, this could be auto-ignored)

Currently, the CO/Smoke detectors are reporting as contact sensors instead of CO/Smoke detectors.

**Comment by ngori** [comment]
@atlcoder Beyond the in esthetics in Homekit is there any benefit/use case for having the device types appear correctly?  I have Nest Protects that are integrated via a different plugin but I don't really see the benefit of having them as Smoke/COs beyond the different icon.  There is no new functionality for me.  We would need to enhance the ADC sensor parsing and add support for the additional Homekit accessory types.

**Comment by dppeak** [comment]
@ngori I would think that beyond the appearance, the proper behavior in reporting and alerts generated within HomeKit would be important.  A contact sensor notice is much different then a Smoke or CO hazard notice.

**Comment by atlcoder** [comment]
The fact that the information is available via the API and that HomeKit supports these devices seems that the plugin should be able to differentiate them. In the end, the functionality is the same or similar.

**Comment by dppeak** [comment]
We have Brinks and the Smoke/CO detectors are connected to the Qolsys IQ Panel 2+.  Would be happy to do testing on the new features.

**Comment by Mikelawry214** [comment]
Please consider adding shades. The api is similar to lights

**Comment by oXb3** [comment]
Is it possible to add the cameras? I noticed a new option within alarm.com for "Advanced Network Setup and Testing". I wasn't sure if that meant we could access the cameras through HomeKit. Thank you so much for this plugin. It is amazing.
![image](https://user-images.githubusercontent.com/57910217/165366007-bf5a87b7-3aaa-49f0-9e76-789758d79671.png)

**Comment by JohnMurwin** [comment]
Is there an update on Thermostat integration?

**Comment by stemow** [comment]
Would love to see thermostat support for the most basic of features on, off, hot, cold, etc. I realize it’s probably another magnitude of complexity, though.

**Comment by chase9** [comment]
HUGE thank you to @pb30 who implemented thermostat support in #111. This has been merged into the beta branch and, if everything goes well, we will finally be able to close this issue!
