### ISSUE TITLE
Locks and garage report proper status on startup, but report the wrong status "Unlocking..." after ~1 min

### ISSUE THREAD

**Issue by majorgearhead** [node-alarm-dot-com/homebridge-node-alarm-dot-com#50]
**Info:**    
```
OS: Raspbian GNU/Linux Buster (10) (Ready made image)
Homebridge Version: v1.1.6
Node.js Version: v14.15.0
Npm Version: v6.14.8
homebridge-node-alarm-dot-com Version:  v1.6.5
Alarm.com Company: CPI Security
```
**Console Errors:**
```
[08/11/2020, 18:24:53] [Security System] Updating light Garage Door (97124791-1201), state=1, prev=0
[08/11/2020, 18:24:53] [Security System] TypeError: Cannot read property 'getCharacteristic' of undefined
    at ADCPlatform.statLightState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:793:9)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:299:20
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:294:27
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:265:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)```
```

**Problem:**
- After I set up the plugin, all three of my door locks (Front Door, Back Door and Garage Door), and my garage door (overhead door) show up in the Home app.  I can operate them from the app.  About a minute in I get errors like above and all of the accessories start going into an "unlocking" state.  Additionally, the Garage door shows as open.  If I restart the server it goes back to normal but goes bad after a minute.
- The state change mentioned in the logs above never happened, I did not open or close the garage.
- the getCharactoristic was just included to show the errors around this.  I think this is just related to the fact that I don't have any switches on my system, but I could be wrong.
- I have gone through removing cache (with homebridge stopped), uninstalling and reinstalling the plugin, ignoring certain devices but to no avail.

Searched issues and I did not immediately find one that was identical to this.  Wondering if I could get an assist on this in your spare time.  My coding skills outside of Python are poor, so not exactly sure where to look.  Any help would be appreciated.

**Comment by ngori** [comment]
Hi,  Your issue looks similar to closed issue #47 which I believe was caused by an incorrect setup on the alarm.com/installer side? I believe in that case the garage door was setup as an door lock?   In your case plugin seems to have your garage door as light which is causing the TypeError.    Did you read through the thread on #47?

**Comment by majorgearhead** [comment]
> Hi,  Your issue looks similar to closed issue #47 which I believe was caused by an incorrect setup on the alarm.com/installer side? I believe in that case the garage door was setup as an door lock?   In your case plugin seems to have your garage door as light which is causing the TypeError.    Did you read through the thread on #47?

I did look through this. In my case even the regular door locks report in the logs with the word light. I just posted the one to show the error.  

I guess I am at a loss as to what to do at this point. Is it suggested to call them and have them "fix" my config?

**Comment by majorgearhead** [comment]
Looking at the data in The ADC cache file it appears that they shifted everything up one. Sensor class has proper dictionaries, lights should have none but has my locks, locks should have my locks but had my garage overhead door, garage should have my overhead door but has nothing. Awaiting a call back from their tech support to work through rectifying this. I just hope I get someone who understands the back end. I will report back what they had to do in hopes this will also help someone else who's provider messed things up.

**Comment by ngori** [comment]
Hmm. Perhaps try seeing how Paul in the previous issue was able to resolve with his provider/installer. As Mike mentioned, the only way to resolve this would be to rewrite the parser which is beyond my ability and time constraints these days. 

I am curious if you had this plugin working correctly before the garage door implementation or are new to it and this was the initial behavior?

**Comment by majorgearhead** [comment]
Background.  I am new to this project and have not run the previous code without the garage doors.  I will attempt that now to see if things start working.

I have tried to work through CPI and the partner tech support at Alarm.com.  Both of them went over my data and said everything was in the proper place on their side.  I explained what was happening and they could not cooperate what I saw.

I am attaching my zipped up ADC-SystemStates.json.  From it you can see that everything appears to be shifted up one:
Locks are in Lights
Garages are in Locks
And the Garages section is empty.

I wonder if:
https://www.alarm.com/web/api/devices/lights/ returns locks
https://www.alarm.com/web/api/devices/locks/ returns garages
https://www.alarm.com/web/api/devices/garageDoors/ returns nothing []

**Would you happen to have an easy way with curl or something else to hit these urls so I can test them and see what they are returning?**  I am not very familiar with the language that was used in this project so it would take me a long while to break down how that works so I could test.

In the mean time I will reach out to the other user to see if they resolved this through their provider.  Thank you for your time!

[ADC-SystemStates.json.zip](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/files/5520731/ADC-SystemStates.json.zip)

**Comment by majorgearhead** [comment]
I started to trace out te calls with wrapapi and all of my lock calls come in with `https://www.alarm.com/web/api/devices/locks/`  and garageDoor calls come in with `https://www.alarm.com/web/api/devices/garageDoors/` so at this point I am really not sure where the issue lies.

**Comment by majorgearhead** [comment]
Update: I locally modified the code for homebridge-node-alarm-dot-com as well as the module code in node-alarm-dot-com and was able to fix this issue for CPI.  Based on the opinion and permission these repo owners, I can fork this into a different project variant for CPI security.

**Comment by chase9** [comment]
William,

Would you be able to push your code to a fork for me to review? As far as I know, no partner should have a layout different in such a way where it’s not comparable entirely.

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by majorgearhead** [comment]
> William,
> 
> Would you be able to push your code to a fork for me to review? As far as I know, no partner should have a layout different in such a way where it’s not comparable entirely.
> 
> Chase Lau

I will commit those changes to a fork this morning. The issue I found is that the code for both the plug-in and associated module expects data to return in the following order:
- Partitions
- Sensors
- Lights
- Locks
- Garages

CPI (var of Alarm.com) presents data in this order:
- Partitions
- Sensors
- Locks
- Garages
- Lights

The temp fix was to reorder those. A more permanent fix would be to detect the order of major devices and work accordingly. This would actually fix this for all of the other people whose Alarm.com vars present data out of order.

**Comment by majorgearhead** [comment]
Please see my forks as requested:

# node-alarm-dot-com
https://github.com/majorgearhead/node-alarm-dot-com/commit/4ea852c9a6dfa7a029151d60f8ad8b2a9e6044e1#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

# homebridge-node-alarm-dot-com
https://github.com/majorgearhead/homebridge-node-alarm-dot-com/commit/def5e64a13fb6854f9d92cb2d5707313bcbd541c#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

**Comment by ngori** [comment]
This is very interesting.  I'm wondering if the order has to do with the order they were added to ADC? I believe but I can't be certain that the original order was the order we added the different device types to our system.

**Comment by chase9** [comment]
I'm hoping to have some more time to look at this today, but right away I notice homebridge-node-alarm-dot-com/index.ts (I'm working in the typescript branch) line 161:
`let realDeviceType = deviceType.split('/')[1];`

This is one of the only places where the system object is referred to by index. Perhaps somehow you having a different order is causing trouble here? In the alarm.com tech portal I only see objects having IDs for Z-Wave, so I'm not sure why another provider would have a different order. This seems to me like a oddity with alarm.com themselves.

I also remember a while back there was a code issue with lights and locks being switched. Sounds dumb, but make sure you're not running out of date code anywhere.

**Comment by wesbro** [comment]
I haven't been using this plugin for the past few months, but I've uninstalled and re-added it to my setup. I'm having similar problems (garage says it's open, but it's not really, and the constant doors "unlocking"). I'm running homebridge-node-alarm-dot-com v1.6.5 and my alarm.com company is Brinks. I'm running this on a HOOBS box (HOOBS Core v3.2.10).

**Comment by iBanks3** [comment]
After updating Node.JS to version 14.15.1 yesterday is when the Garage Door began to display as opened though it’s not. I have noticed the “door unlocked” notifications prior to that Node.JS update but it was infrequent for me so didn’t think much of it.

**Comment by majorgearhead** [comment]
> I'm hoping to have some more time to look at this today, but right away I notice homebridge-node-alarm-dot-com/index.ts (I'm working in the typescript branch) line 161:
> 
> `let realDeviceType = deviceType.split('/')[1];`
> 
> 
> 
> This is one of the only places where the system object is referred to by index. Perhaps somehow you having a different order is causing trouble here? In the alarm.com tech portal I only see objects having IDs for Z-Wave, so I'm not sure why another provider would have a different order. This seems to me like a oddity with alarm.com themselves.
> 
> 
> 
> I also remember a while back there was a code issue with lights and locks being switched. Sounds dumb, but make sure you're not running out of date code anywhere.

I am running the very latest code.  That let realDeviceTypes looks like it deals with the actual device types that are passed.  At issue is that CPI and other VAR's seem to be passing groups of these in an order different from what this code expects.  Like I said before, was able to fix this issue by just doing the reorder found in my fork above.  This looks like it could be a solution for others who have complained of the same thing like garage-door reporting open when it is closed.

The real solution would be to refactor to not expect a static order, but dynamic based on the deviceType.

For now I am happily running my fork of the code and it has worked perfectly since making the change.

**Comment by chase9** [comment]
I'm still very confused by that's going on here. The only thing I can think of is that because the system state is returned into an array, if you're missing one of those device types, that's where the shift could happen? I'm thinking about changing some of the primitives into objects and seeing if not using indexing will fix the problem.

**Comment by chase9** [comment]
@majorgearhead There have been some changes to how we retrieve objects, which have been merged since this issue was opened. Could you tell me if you're still experiencing this issue when running the latest version of the plugin?

**Comment by majorgearhead** [comment]
> @majorgearhead There have been some changes to how we retrieve objects, which have been merged since this issue was opened. Could you tell me if you're still experiencing this issue when running the latest version of the plugin?

The problem is not fixed and still gives the same error messages.  I am now restoring from backup to back back to my working config.  The issue has always been with the hardcoding of accessory order.  Accessories need to be dynamically pulled in based on what they are not perceived order they will come in.

**Comment by majorgearhead** [comment]
Unfortunately, I did not have a viable backup, and even installing the old plugin will pull in the new module which breaks with this error.  I am dead in the water now until I find a way to hack things up to get this working.

```TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:1291:32)
    at ADCPlatform.statPartitionState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:435:19)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:273:20
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:268:31
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:265:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by majorgearhead** [comment]
I hacked things up to get it working again.  I had to do exactly what I did before, moving lights stanzas after garages wherever they both appeared in:
/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/dist/index.js
/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js

diff's to follow shortly...

**Comment by chase9** [comment]
Hi @majorgearhead. Version 1.8.0 has been released with code that should fix the issue with devices getting mixed up. I know it's been a while, but if you're still around, could you test and close this issue if it's no longer present? Thank you!

**Comment by majorgearhead** [comment]
I sure can. I have a little other work to do tonight but would be happy to test and report back. Thanks for making the change.

**Comment by majorgearhead** [comment]
This did fix the issue I reported.  All doors and windows now show up properly without me having to make modifications to the code.

Thank you!
