### ISSUE TITLE
GET error

### ISSUE THREAD

**Issue by derekschinke** [node-alarm-dot-com/homebridge-node-alarm-dot-com#51]
**Describe the bug**
This plugin doesn't seem to be connecting to Alarm.com. Here's the log.

Error: GET https://www.alarm.com/web/api/systems/systems/7521917 failed: [object Object]
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:544:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

It repeats ad infinitum, every few seconds.

**To Reproduce**
I installed homebridge, installed this plugin, input my login and settings (which are correct), and this happens.

**Expected behavior**
It connects to the Alarm.com API and lets me access devices.

**ADC-SystemStates.json**
This does not exist in the same folder as my Homebridge config.json file with Log Level set to 4.

**Homebridge System (please complete the following information):**
* **Node.js Version**: v14.15.1
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.1.6
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Additional context**

**Comment by ngori** [comment]
Hi, a couple questions.  Did you previously have the plugin setup and working as expected?  Can you confirm you don't have two factor authentication enabled with your alarm.com provider?

**Comment by mbmarlowe** [comment]
Hello, first time user of the plugin just freshly installed.  I have this same error with all of the same information.  My errors are the same, but I just noticed the comment and 2FA is enabled.  Am I to take it 2FA must be disabled?  I will try that now and confirm and reply if that fixes it.

**Comment by mbmarlowe** [comment]
Disabling 2FA fixed the issue for me.  So, that is probably the same reasoning for the original requestor.

**Comment by chase9** [comment]
2FA is unfortunately not compatible with the plugin at this time. Alarm.com doesn't have any sort of "app password", and the work hasn't been put in to mimic their login process (namely because it's really hard to mimic an interactive process on the server-side!)

**Comment by derekschinke** [comment]
Oops, you're right, I have 2FA enabled. I was logging in on my desktop browser and thought it only needed a password (I guess it remembered me), but after trying to login on my phone, it asked for a 2FA code. Thank you for your help!
