### ISSUE TITLE
Status icon on the Home app shows OFF even when system is set to Home or Away

### ISSUE THREAD

**Issue by namanshah76** [node-alarm-dot-com/homebridge-node-alarm-dot-com#53]
**Describe the bug**
Status icon on top of the Home app always shows OFF even when the system is set to Home or Away. The accessory tile does show correct status. 

**To Reproduce**
1. Open Home App
2. Check status icon in Home app.
3. If I restart the Home app after arming, the status icon briefly shows correct status (see attached screenshot) and then changes to OFF.

**Expected behavior**
Icon should reflect the correct state of the system - OFF, HOME, AWAY

**Screenshots**
INCORRECT STATUS ICON
![incorrect](https://user-images.githubusercontent.com/36424865/103710376-dc949580-4f82-11eb-906d-f1c5ca63d064.png)

CORRECT STATUS SHOWS BRIEFLY AFTER RESTARTING THE HOME APP
![correct](https://user-images.githubusercontent.com/36424865/103710384-e0c0b300-4f82-11eb-8d0e-623b4fbb7d80.png)

**ADC-SystemStates.json**

**Homebridge System (please complete the following information):**
* **Node.js Version**: 14.15.3
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.1.7
* **Operating System**: Windows
* **Process Supervisor**: Windows Service

**Additional context**

**Comment by chase9** [comment]
Hello,

This bug it quite old and there have been new versions since this was filed. Please let me know if this is still an issue with the latest version of the plugin.
