### ISSUE TITLE
Repeated errors with typescript

### ISSUE THREAD

**Issue by ifeign** [node-alarm-dot-com/homebridge-node-alarm-dot-com#56]
**Describe the bug**

Many errors when updating to latest version
**To Reproduce**

update to 1.7.0
```

 [2/6/2021, 1:49:02 PM] [Security System] TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1295:24)
    at ADCPlatform.statPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:449:19)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:301:20
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:296:31
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:293:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/6/2021, 1:49:48 PM] [Security System] changePartitionState(94218683-127, 3)
[2/6/2021, 1:49:49 PM] [Security System] Error: Failed to change partition state: TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1295:24)
    at ADCPlatform.statPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:449:19)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:530:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/6/2021, 1:49:50 PM] [Security System] TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1295:24)
    at ADCPlatform.statPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:449:19)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:301:20
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:296:31
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:293:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/6/2021, 1:50:02 PM] [Security System] TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1295:24)
    at ADCPlatform.statPartitionState (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:449:19)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:301:20
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:296:31
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:293:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by davidvanvo** [comment]
Confirmed. Seeing similar errors.

2/6/2021, 4:01:37 PM [Security System] TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/dist/index.js:1062:49)
    at ADCPlatform.statPartitionState (/home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/dist/index.js:351:23)
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/dist/index.js:221:30
    at Array.forEach (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/dist/index.js:216:39
    at Array.forEach (<anonymous>)
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/dist/index.js:214:26
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by ifeign** [comment]
What is extra weird is when I tried to roll back to a previous version, I still get these errors. What's happening?

**Comment by chase9** [comment]
Hi guys, I unfortunately didn't get the imports right in the last release. I'm aware of the problem and trying to fix it now.

**Comment by ifeign** [comment]
So.. this is beyond weird. I uninstalled the plugin and re-insalled the previous 1.6.5 version, now none of my contact sensors are showing up and the alarm system just isn't working.. what could have caused this?

**Comment by chase9** [comment]
Glad to hear it! Sorry for any inconvenience this has caused you.

**Comment by ifeign** [comment]
> Glad to hear it! Sorry for any inconvenience this has caused you.

All good! That's the risk I take by updating 30 mins after a release 😂

**Comment by ifeign** [comment]
I may have spoken too soon, this is the new error when I try to arm:

```
[2/6/2021, 2:30:54 PM] [Security System] Error: Failed to change partition state: Error: POST https://www.alarm.com/web/api/devices/partitions/94218683-127/armStay failed: 422
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:493:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by autopear** [comment]
Unfortunately, it shows the same error in 1.7.1.

`[FrontPoint] TypeError: Cannot read property 'ARMED_STAY' of undefined
    at getPartitionState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1295:24)
    at ADCPlatform.statPartitionState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:449:19)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:301:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:296:31
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:293:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by chase9** [comment]
To make sure there's nothing left over from the bunk, could you remove the plugin, re-add it (it'll keep your configuration, don't worry), then restart homebridge? Arming and disarming is working fine from my end.

**Comment by ifeign** [comment]
> To make sure there's nothing left over from the bunk, could you remove the plugin, re-add it (it'll keep your configuration, don't worry), then restart homebridge? Arming and disarming is working fine from my end.

That's what I did, I completely removed the config too. I'm using a Frontpoint system if that makes any difference - but it never has in the past

**Comment by iBanks3** [comment]
I too removed plugin, restarted server then reinstalled v1.7.1 and still same error. Also tried to enable 2FA but still the same error.

**Comment by chase9** [comment]
Did you mean to say _disable_ 2FA?  If so, 2FA isn't supported in this release but I'll shoot for the next.

**Comment by ifeign** [comment]
This is driving me nuts, the current version won't arm, meanwhile if I revert to 1.6.5 or 1.6.4 the plugin also acts super weird. When I revert, I still see errors and everything is unresponsive, so now I've just got a broken accessory

**Comment by iBanks3** [comment]
I enabled it. It was disabled all along but I enabled it to see if it would bypass the error and due to no change in error I went in and disabled 2FA again.

**Comment by ifeign** [comment]
I've determined that it just can't use Night Mode in the Home app, but Away and Home seem fine. Stupid me for not trying other modes. Neither of them respect my silent arming setting though

**Comment by ifeign** [comment]
Also, have you noticed that the new version breaks the config schema? Now when I hit settings, it just shows the json script

**Comment by chase9** [comment]
@ifeign The reason you're having trouble reverting is because this plugin also relies on `node-alarm-dot-com`. I talk about how to revert [here](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/54#issuecomment-758825470).

Glad to see the other modes work. That patch was submitted by someone else who might have had a different provider. If you would be willing to check and see what API call your provider uses for night mode I would be super grateful. 

I didn't notice that it breaks the config schema, I'll check that out. Would you mind making a different issue for that?

**Comment by ifeign** [comment]
> @ifeign The reason you're having trouble reverting is because this plugin also relies on `node-alarm-dot-com`. I talk about how to revert [here](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/54#issuecomment-758825470).
> 
> Glad to see the other modes work. That patch was submitted by someone else who might have had a different provider. If you would be willing to check and see what API call your provider uses for night mode I would be super grateful.
> 
> I didn't notice that it breaks the config schema, I'll check that out. Would you mind making a different issue for that?

How would I check that API call? All I can say is it worked before, this old plugin might have insight https://www.npmjs.com/package/homebridge-frontpoint

**Comment by davidvanvo** [comment]
@ifeign 1.71 fix update worked for me, but I also don't have frontpoint.

**Comment by ifeign** [comment]
> @ifeign The reason you're having trouble reverting is because this plugin also relies on `node-alarm-dot-com`. I talk about how to revert [here](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/54#issuecomment-758825470).

I'm trying to uninstall node-alarm-dot-cop 1.10.0 and replace it with the previous version and it keeps showing up when I run npm list. I just can't seem to remove it, so I guess I'll have to live with a semi-broken plugin til night mode gets fixed. I think the fact that I'm running the dockerized version of homebridge isn't helping with this.

**Comment by chase9** [comment]
@ifeign I've tracked down the cause of the issue and I can fix it tomorrow. Basically, the fix for night mode includes a variable which alarm.com doesn't know how to handle (it doesn't appear alarm.com actually differentiates with a night arm). Could you just tell me if your alarm.com partition has a night mode or is it just Disarm/Stay/Away?

**Comment by ngori** [comment]
@chase9 if I recall correctly "night mode" is just arm stay with silent arming enabled? It's not an explicit alarm.com state

**Comment by ifeign** [comment]
I’m just referring to Night in the Home app, which should just trigger Stay
mode, but currently is broken with the latest update with the error I
posted above

**Comment by chase9** [comment]
I’m just trying to figure out why the person who submitted the PR added a night parameter and said it was working for them. I agree that night mode is probably just stay with silent arming turned on. Maybe it was unique to their provider?

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by ifeign** [comment]
I’m a little confused too, especially considering everything worked fine
last night before I updated this plugin. Is there nothing that can be done?

**Comment by chase9** [comment]
No worries, this can be fixed tomorrow. I’m just wondering the best way to fix it :)

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by ifeign** [comment]
Awesome thanks for your hard work

**Comment by chase9** [comment]
I've updated the beta branch so that the night arm mode should be working again. For users who have a panel that supports night arming, you'll have to set the appropriate check in your config. Please update to the beta branch and let me know if you run into any more problems!

[Here's how to update to alternate plugin versions from the UI](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)
