### ISSUE TITLE
Since updating receiving error: "Error: The requested platform 'Alarmdotcom' was not registered by any plugin."

### ISSUE THREAD

**Issue by mfczureal** [node-alarm-dot-com/homebridge-node-alarm-dot-com#58]
**Describe the bug**
Updated plugin to newest version (1.7.1) this morning and now the plugin will not load and Homebridge/HOOBS will not start

**To Reproduce**
Configure plugin, save, plugin will not start

**Expected behavior**
Hoobs will start and plugin will function

**Screenshots**
2/7/2021, 9:49:59 AM Error: The requested platform 'Alarmdotcom' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**ADC-SystemStates.json**
Not sure how to get this one in Hoobs.  

**Homebridge System (please complete the following information):**
* **Node.js Version**: v12.19.0
* **NPM Version**: 7.5.2
* **Homebridge Version**: Hoobs 3,3.2
* **Operating System**: Fedora 29
* **Process Supervisor**: Systemd

**Additional context**

**Comment by chase9** [comment]
Could you upload your config here for me to view? Please remember to redact any usernames and passwords when you upload it. Thanks!

**Comment by mfczureal** [comment]
{
    "platform": "Alarmdotcom",
    "name": "Security System",
    "username": "<username>",
    "password": "<password>",
    "armingModes": {
        "away": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "home": {
            "noEntryDelay": false,
            "silentArming": false
        }
    },
    "ignoredDevices": [
        "96922426-1",
        "96922426-4"
    ]
}

**Comment by mfczureal** [comment]
Well, I uninstalled and reinstalled the plugin a couple of times, did a manual npm install homebridge-node-alarm-dot-com and reapplied the "arming modes" portion of the configuration file and it seems to be working now.  I have no explanation on how I managed to fix it, but it seems to be working fine now.  Sorry.

**Comment by mfczureal** [comment]
Uninstalling and reinstalling several times as well as recreating my configuration file seems to have fixed the problem
