### ISSUE TITLE
Night option worked with 1.6.5 but not latest 

### ISSUE THREAD

**Issue by anthonyb82** [node-alarm-dot-com/homebridge-node-alarm-dot-com#60]
**Describe the bug**
on previous version, 1.6.5, the “night” option in homekit allowed my panel to set with the “sleep” mode, which I had configured slightly differently than “home mode” (both silent armed, “home” would have an entry delay and sleep would not. Since update, “night” will no longer read (see error below). Unfortunately reverting back to 1.6.5 is now causing no response errors, so that’s not an option. I know the “sleep” or “night” mode have been called out as not working with alarm.com, but it was working flawlessly for me before. Wanted to call it out in case there was a clue in 1.6.5 that got it to work. 

**Expected behavior**

**Screenshots**

**ADC-SystemStates.json**
This is the error I now get that I didn’t before: 

Error: Failed to change partition state: Error: POST https://www.alarm.com/web/api/devices/partitions/100533361-127/armStay failed: 422
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:493:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
>

**Homebridge System (please complete the following information):**
* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.10
* **Homebridge Version**: 1.1.7
* **Operating System**: Raspbian

**Comment by anthonyb82** [comment]
Sorry, after reading through some of the details of the other issues, it looks like this may be something you are aware of and working on. If I can provide any info to help, please let me know. I previously had the “sleep” button working properly with both a Frontpoint and surety system. Appreciate it!

**Comment by chase9** [comment]
I've updated the beta branch so that the night arm mode should be working again. For users who have a panel that supports night arming, you'll have to set the appropriate check in your config. Please update to the beta branch and let me know if you run into any more problems!

[Here's how to update to alternate plugin versions from the UI](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)

**Comment by anthonyb82** [comment]
Beta is working just as expected again. Thank you so much for your efforts on this plug-in and getting this resolved so quickly!
