### ISSUE TITLE
Sensor with unknown state since 1.7.1

### ISSUE THREAD

**Issue by matellis** [node-alarm-dot-com/homebridge-node-alarm-dot-com#61]
**Everything is working correctly.**

See this error in my logs a lot since the update to 1.7.1

`[2/13/2021, 13:02:32] [Frontpoint] Warning: Sensor with unknown state 0`

Let me know if I can provide additional debug info. Nothing seems to be broken, just getting the error.

**Comment by macjbraun** [comment]
Same error here. No changes to hardware or homebridge. I downgraded to 1.7.0 then 1.6.5 and removed cached accessories and the error persists

**Comment by chase9** [comment]
Could you provide a list of your sensors? I believe this can be retrieved by bumping up your logging level and looking for the file cached-accessories.json (it will tell you it’s saving in the log)

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by macjbraun** [comment]
I have the same problem. I ignored all sensors and still get the problem. I downgraded to 1.7.0 and those errors go away but Arm-Stay issue shows up.

**Comment by matellis** [comment]
I stopped the service and ran `homebridge -D` via ssh and cannot find `cached-accessories.json` I do have `cachedAccessories` (no extension) in `~/.homebridge/accessories` Is that what you are looking for? I did not see another way of running in debug mode and I did *not* see any notification that it was saving in the log to `cached-accessories.json`. Pls advise if there's a different way of getting you this data. Thanks

**Comment by macjbraun** [comment]
[cachedAccessories.txt](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/files/5978423/cachedAccessories.txt)

**Comment by matellis** [comment]
[cachedAccessories.txt](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/files/5978442/cachedAccessories.txt)

**Comment by andrewheavin** [comment]
I actually had a similar issue and submitted a pull request #68 to add additional detail to the logging, to help users identify which device is having the issue. For me it's the glassbreak sensors that are returning a state of 0, which get mapped to Unknown type.

**Comment by matellis** [comment]
I have some glassbreak sensors, so that makes sense. FWIW @chase9 has commented there’s something coming in v1.8.0 that should address this.

**Comment by chase9** [comment]
Looking at this now it appears to be a symptom of alarm.com not following a spec I can make sense of (which, I suppose, is why they don't have a public API :P )

So far I've noticed that Glassbreak, (some) Keyfobs, and (some) glassbreaks report their status as 0 when they're fine. Could you check in the alarm.com portal > sensors to make sure these statuses are "OK" without any other complaints about the system needing a reset?

**Comment by arkadiysudarikov** [comment]
Seeing this too, - diagnostics were fine and motion detector is working, - my warning: "Sensor Motion Detector has unknown state"

**Comment by chase9** [comment]
Hello, doing some housekeeping here. Is anyone still having this issue?
