### ISSUE TITLE
Unstable Usage with 2FA, Beta 1.7.2.4

### ISSUE THREAD

**Issue by techfreakdad** [node-alarm-dot-com/homebridge-node-alarm-dot-com#66]
After Alarm.com switched to 2FA, I started using the 1.7.2.4 Beta plugin following the instructions to insert the 2FA Cookie from Alarm.com website. Since then, behavior of alarm panel (that previously worked), no longer triggers, as well, Ignored Devices are not being recognized in HomeKit. 

From Logs:

Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=96741200-3&ids%5B%5D=96741200-6&ids%5B%5D=96741200-1&ids%5B%5D=96741200-59&ids%5B%5D=96741200-8&ids%5B%5D=96741200-5&ids%5B%5D=96741200-2&ids%5B%5D=96741200-7&ids%5B%5D=96741200-4 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=96741200-3&ids%5B%5D=96741200-6&ids%5B%5D=96741200-1&ids%5B%5D=96741200-59&ids%5B%5D=96741200-8&ids%5B%5D=96741200-5&ids%5B%5D=96741200-2&ids%5B%5D=96741200-7&ids%5B%5D=96741200-4 failed, reason: read ECONNRESET
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:470:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)

**Homebridge System (please complete the following information):*
* **NPM Version**: 14.16.0
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: none

**Comment by danTHAman152000** [comment]
I am getting a similar error. I have been getting errors lately but the alarm was still functioning in HK until tonight. I updated to the Beta and also enabled 2FA, and seems to be functioning but getting this new error.

**Comment by chase9** [comment]
I'm stumped on how this doesn't seem to discriminate on provider, plugin version, or MFA usage. It's also odd that at least some people still have working setups while receiving this error. I'm wondering if alarm.com has changed their API limits and are starting so soft block some of our connections?

FWIW, here's my  (working) refresh time:
Timeout to Re-Authenticate Session: 10
Device Polling Interval: 60

Anyone have more ideas on how to troubleshoot this?

**Comment by aujosh02** [comment]
I'm having this issue as well but mine stopped working altogether. I uninstalled and have been checking here daily to see if the issue has been resolved.

**Comment by lsustang05** [comment]
I am having this same issue. Everything worked until yesterday and then I guess alarm.com required 2FA. Enabled, plugged in the 2FA cookie which cleared that issue, but now this issue is popping up and the system does not work at all.

**Comment by DMBlakeley** [comment]
Started receiving this error today. Obtained new 2FA code and configuration followed by reboot. No improvement.

*Homebridge System (please complete the following information):

Node.js Version: 14.17.0
NPM Version: 6.14.13
Homebridge Version: 1.3.4
Operating System: MacOS
Process Supervisor: none

**Comment by DMBlakeley** [comment]
Updated to NPM Version 7.13.0 and problem seems to have been addressed. Will continue to monitor.

**Comment by chase9** [comment]
I'm closing this thread to consolidate discussion in #72
