### ISSUE TITLE
GE Light switch won't turn on

### ISSUE THREAD

**Issue by Nbr1Sniper** [node-alarm-dot-com/homebridge-node-alarm-dot-com#69]
Hi,

I have 3 Z-Wave GE light switches and a zooz. All of them work as designed expect for one of the GE switches. The switch turns on and off without and issues using my alarm panel. If I use the HomeBridge system it will only turn it off. It will NOT turn it on.  What can I do to fix the problem? Can you fix something within the app?

**Comment by chase9** [comment]
Please recreate your issue and then upload your logs showing the problem. Hard to diagnose without more information. Thank you!

**Comment by chase9** [comment]
Closing due to lack of response. Based on the other thread I think your issue is ECONNECT
