### ISSUE TITLE
Silent Arming, No Entry Delay, Bypass Open Sensors

### ISSUE THREAD

**Issue by mkormendy** [node-alarm-dot-com/homebridge-node-alarm-dot-com#7]
Need to fully test and fix the following options if they aren't working properly:

- Silent Arming
- No Entry Delay
- Bypass Open Sensors

Some possible reasons why this may not be working is due to the use of the mobile version of the website not including this option/setting, per Bryan's plugin findings [here](https://github.com/bryan-bartow/homebridge-alarm.com/issues/6#issuecomment-207415087) and [here](https://github.com/bryan-bartow/homebridge-alarm.com/issues/25#issuecomment-232129324).

**Comment by Tangston311** [comment]
Just wanted to check on the status of this guy - I'm currently using the jhurliman/frontpoint plugin and would like to switch to this one so I can hide sensors I don't need in the app, but Silent Arming is something that I currently use in my automations so it'd be a bummer to lose that.  Is it not working for everyone, or just for some people/certain platforms?

**Comment by mkormendy** [comment]
@Tangston311 I'm assuming you're a customer with FrontPoint? .. and you can Silent Arm with that?

**Comment by Tangston311** [comment]
@mkormendy , I am, and yes (through their app natively, and silent arming also works with the jhurliman plugin, so I was just curious if there were known issues that would cause it not to work with this plugin as well).

**Comment by mkormendy** [comment]
With my setup, I am a customer of an Alarm.com provider called Security Assistant here in Dallas. There are 4 modes that present themselves in the Home app: Home, Away, Night, and Off.

- Home: sets the alarm to "Stay" mode, very short beep once and that's it
- Away: sets the alarm to "Away" mode, multiple very short beeps in a countdown sequence
- Night: (virtually the same as Home)
- Off: sets the alarm to "Disarmed" mode, standard disarm beep, once and that's it

With the Home and the Night mode being virtually the same, the only difference is that these can be used to assist with automations depending on which one you want to trigger or have other automations trigger based on their state.

For example, I've never really need to set my alarm to "Stay" with silent arming. In fact, I like to actually hear that very short beep at night, which I have an automation to turn my Night mode on, only when I am home, at 10:30pm every night. To me it's reassuring.

**Comment by Tangston311** [comment]
Gotcha - yeah in my current setup I have "Home" set to Silent Arm because the new Frontpoint hub has a loud, obnoxious voice that says, "SYSTEM ARMED STAY" that wakes up our baby.  You can adjust the volume from the app, but that also turns down the a-sensor-tripped-and-you-have-30-seconds-to-disarm beeps to a volume you can't hear, which winds up with the alarm going off and waking up the baby.  It's a vicious, baby-waking circle.  Silent Arm solves that :)

**Comment by mkormendy** [comment]
There must be a setting to turn off the voice prompts in favor of a beep, I can't imagine every one of their clients would want that.

**Comment by mkormendy** [comment]
@Tangston311 I have added the ability to hide sensors in one of the past updates. As for the Silent Arming, I don't have a fix for this yet. Just wanted to keep you updated.

**Comment by Tangston311** [comment]
@mkormendy thanks for the update!  I've starting using it with my Frontpoint Hub set to mute which has been working well.

**Comment by ifeign** [comment]
I just wanted to report that I use an older Frontpoint system and silent arming etc appear to work as expected.

**Comment by mkormendy** [comment]
@ifeign would you help me verify some things with some testing? I want to see what front point is doing differently. There’s a slack channel on pinned around the top of the issues page with the link to the slack channel.

**Comment by ifeign** [comment]
Sure, I can help out! I’ll get on Slack later today.

**Comment by Haglerd** [comment]
where is the slack channel, I can help test. I want this plugin to work for me, but until the silent arming works I can't use it :(.

**Comment by mkormendy** [comment]
@Haglerd the slack channel is in the issue pinned on the issues page.

**Comment by chase9** [comment]
Right now we rely on a user knowing what features their panel supports. However, _somehow_ Alarm.com is able to adapt calls based on supported features.

A quick look at the API calls the website makes for me shows that when retrieving partition state, there are two interesting values:
```
extendedArmingOptions: ...
invalidExtendedArmingOptions: ...
```

However, these just have a bunch of numbers in arrays, so it's hard for me to tell what's going on.

**Comment by twentyNoise** [comment]
Has there been any further investigation into Silent Arming?

I'm using Alarm.com and I'm able to Silent Alarm from my panel but the Silent Arming through the Alarm.com App and this Homebridge plugin has never worked.

Thanks!

**Comment by scottleestrange** [comment]
Setting "Bypass Open Sensors" is something that needs added to the plugin.  I have been asking for a while now.  In my Alarm.com it is called "Force Bypass".  This is how I would typically arm for night.  In good weather we like to keep some upstairs windows open.

I am not sure how to check out and update the code so some help would be appreciated

**Comment by chase9** [comment]
@twentyNoise We already support silent arming in the config for the plugin. Are you saying you've tried it but it's not working?

**Comment by ojoaosemtil** [comment]
Is it still not working silent arming? I tried and It still beeps, but I can do it through alarm.com website and the app.

**Comment by tallrals** [comment]
Not the original poster, but I have tried silent arming and it doesn't work for any of the arming modes. I have tried silent arming on each mode and my panel still announces which mode has been activated. My panel was originally installed by Reliant Energy, but was recently taken over by ADT. It has used the alarm.com platform the entire time though.

On a side note, I have noticed that the arming modes listed in the plugin don't match what shows up in the Home app. It appears that "Stay" in the plugin is "Home" in the Home app. Also, when I select "Night" in the Home app, it will arm as "Stay" from the panel and then change to "Home" in the app, so it appears they do the same thing. 

I'm not sure if there is a way to solve this, but I wanted to bring it up. I just setup my Homebridge a few days ago so I'm still learning how everything works. Thanks for all of your hard work!

**Comment by chase9** [comment]
Ok, coming back to this.

Stay and Night arm are indeed the same thing, as far as the plugin is involved. The difference is that we allow you to set different values for noEntryDelay, silentArming, and nightArming.

I recently got a new panel with these fancy features, so I will be adding these to the next release.

**Comment by chase9** [comment]
@tallrals Has the latest version fixed silent arming for you? If not, I would need to see a screenshot of what your alarm.com portal looks like when performing a silent arm.

**Comment by chase9** [comment]
I'm going to close this due to inactivity. Happy to implement the silent arming feature if someone says they're still having an issue!

**Comment by tallrals** [comment]
I just wanted to add to this thread. I just tested everything again and the "Silent Alarming" option still had the voice announcement, but the "Night Arming" option did in fact set the alarm silently. I'm not sure what the difference between those two options is, but at least it's working. I'm sure it's a mater of how my system has gone through a few different providers by this point, but the Silent and Night options are a little confusing.

**Comment by cuculito** [comment]
After running into this myself, here's my attempt at a bit of clarity:

Personally, I have CPI's flavor of Alarm.com. 
The plugin exposes 3 sections: Away, Night, Stay. 
For each of those sections, 3 options are presented: No Entry Delay, Silent Arming, Night Arming

I have not tested No Entry Delay at all as I don't use that feature
Silent Arming does not seem to affect anything. On or Off I have the chime countdown on my panel for Away/Night/Stay.
Night Arming seems to actually do a Silent Arm. 

So the way I personally have it set is:

Away -> Silent Arming (probably moot as I don't believe it does anything)

Night -> Silent Arming + Night Arming (This does a silent arm then immediately becomes 'Stay'. On the home app it's presented as selecting 'Night' and within seconds it transitions to 'Home' aka "Stay"
Stay

Stay-> Silent Arming. This is just my way to activate Stay (aka Home in HomeKit) with the beeping countdown on the panel

After writing all this down I now don't believe this really clarifies anything, but here's hoping!

**Comment by Fodera123** [comment]
Hey guys, Looks I'm having something similar. Here's my latest logs.

So far I can use the home and disarmed mode but away isn't working.

<img width="1512" alt="Capture d’écran, le 2024-12-26 à 21 35 00" src="https://github.com/user-attachments/assets/71ab668f-6779-4b98-9b35-fe7b53a322b8" />

**Comment by Fodera123** [comment]
Yep, worked fine. The countdown is back is "Away mode" but I putted it in Silent mode and now it's running silently.
Here's my setup on this one and it's working pretty fine with me now.

Thanks

<img width="1512" alt="Capture d’écran, le 2024-12-29 à 15 17 19" src="https://github.com/user-attachments/assets/599dec46-38a3-418b-8b4b-445c86553d1c" />
