### ISSUE TITLE
New User Setup Help

### ISSUE THREAD

**Issue by JCallender73** [node-alarm-dot-com/homebridge-node-alarm-dot-com#70]
**Describe the bug**

Current Config
{
    "platform": "Alarmdotcom",
    "name": "Security System",
    "username": "<XXXXXX",
    "password": "<XXXX>",
    "armingModes": {
        "away": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "night": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "stay": {
            "noEntryDelay": false,
            "silentArming": false
        }
    },
    "logLevel": 1
}

4/14/2021, 9:39:22 PM Initializing HAP-NodeJS v0.9.3...
4/14/2021, 9:39:23 PM Loaded plugin 'homebridge-node-alarm-dot-com'
4/14/2021, 9:39:23 PM [4/14/2021, 7:39:23 PM] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
4/14/2021, 9:39:23 PM Loading 1 platforms...
4/14/2021, 9:39:23 PM [Security System] Initializing Alarmdotcom platform...
4/14/2021, 9:39:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com
4/14/2021, 9:39:23 PM Preparing Advertiser for 'HOOBS 7BFA' using bonjour-hap backend!
4/14/2021, 9:39:23 PM Starting to advertise 'HOOBS 7BFA' using bonjour-hap backend!
4/14/2021, 9:39:23 PM Bridge is running on port 51826.
4/14/2021, 9:40:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com
4/14/2021, 9:41:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com
4/14/2021, 9:42:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com
4/14/2021, 9:43:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com
4/14/2021, 9:44:23 PM [Security System] Logging into Alarm.com as <Johnathan.Callender@icloud.com

**Comment by ifeign** [comment]
What is the issue? The plugin has to regularly log into alarm.com to keep the connection active. This log looks normal.

**Comment by chase9** [comment]
@JCallender73 I'm going to delete this issue as it seems like everything is working fine, and you've (accidentally?) uploaded your personal email. If your issue persists, please submit another issue with proper detail and sanitize your log. Thanks!
