### ISSUE TITLE
Add local control for Qolsys IQ panels

### ISSUE THREAD

**Issue by ifeign** [node-alarm-dot-com/homebridge-node-alarm-dot-com#71]
**Is your feature request related to a problem? Please describe.**
One of the main issues with this plugin is stated in the readme:

> Sensors (due to lag and capabilities in Alarm.com's web API, these features are partially supported)

Local polling would solve this for ADC users with Qolsys IQ panels.

**Describe the solution you'd like**
Some Home Assistant users [recently figured out how to get local sensor data from Qolsys panels](https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/1), a popular ADC security touch panel. More specifics about this can be [viewed on their repo](https://github.com/roopesh/ad-qolsys). In addition to all this, one of the users [expressed interest in collaborating with a Homebridge plugin dev](https://reddit.com/r/homebridge/comments/lqszy4/_/gvrwvw2/?context=1) so that it can easily be brought into HomeKit. This would be wonderful as the Home Assistant integration is more technically involved than average. This would dramatically improve the speed and reliability of this plugin when used with Qolsys panels, as well as make sensors, the security system and possibly other accessories work without an internet connection.

**Additional context**
Relevant links:
https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405

https://github.com/roopesh/ad-qolsys

https://reddit.com/r/homebridge/comments/lqszy4/_/gvrwvw2/?context=1

**Comment by jrapczak** [comment]
> **Is your feature request related to a problem? Please describe.**
> One of the main issues with this plugin is stated in the readme:
> 
> > Sensors (due to lag and capabilities in Alarm.com's web API, these features are partially supported)
> 
> Local polling would solve this for ADC users with Qolsys IQ panels.
> 
> **Describe the solution you'd like**
> Some Home Assistant users [recently figured out how to get local sensor data from Qolsys panels](https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/1), a popular ADC security touch panel. More specifics about this can be [viewed on their repo](https://github.com/roopesh/ad-qolsys). In addition to all this, one of the users [expressed interest in collaborating with a Homebridge plugin dev](https://reddit.com/r/homebridge/comments/lqszy4/_/gvrwvw2/?context=1) so that it can easily be brought into HomeKit. This would be wonderful as the Home Assistant integration is more technically involved than average. This would dramatically improve the speed and reliability of this plugin when used with Qolsys panels, as well as make sensors, the security system and possibly other accessories work without an internet connection.
> 
> **Additional context**
> Relevant links:
> https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405
> 
> https://github.com/roopesh/ad-qolsys
> 
> https://reddit.com/r/homebridge/comments/lqszy4/_/gvrwvw2/?context=1

This would be awesome!

**Comment by chase9** [comment]
This would be fantastic, but I unfortunately don't have this panel. I'll see if I can't get my hands on one to test.

**Comment by ifeign** [comment]
If I were more technically inclined I’d give it a try… but if you reach out
to that person I mentioned who is willing to collaborate, they could
probably provide a lot of good insight

**Comment by harryfrishberg** [comment]
I have a Qolsys IQ Panel 2 and would love to help out if it makes this plugin able to function on a local basis, therefore reducing the need to call on Alarm.com's servers. 

Let me know if I can be of use. And thank you Chase for your tremendous work on this project!

**Comment by anthonyb82** [comment]
Same here. The IQ Panel 2 can be had for about $220. I know I’d certainly be willing to chip in on the cost if others were and chase is willing to work on it. It’s a big ask I’m sure.

**Comment by harryfrishberg** [comment]
Count me in! At the very least we could put a considerable dent in the cost of buying one of these panels!

**Comment by chase9** [comment]
I appreciate it guys, but I'm unwilling to commit to this (and especially take any money) until we can solve these ongoing issues. Hope this will be sooner than later!

**Comment by ifeign** [comment]
Understandable, but if and when that is resolved, I’d be happy to chip in for the IQ panel.

**Comment by ifeign** [comment]
It seems people are no longer having (frequent) econnect errors with the beta release. @chase9 are you still interested in exploring this?

**Comment by sup3rm3ga** [comment]
> It seems people are no longer having (frequent) econnect errors with the beta release. @chase9 are you still interested in exploring this?

If it's any help, local control is working with Home Assistant via AppDaemon and MQTT as per [here](https://github.com/roopesh/ad-qolsys). Home Assistant HomeKit Bridge allows this to show up in HomeKit so I have it on my phone, although I primarily use it with Home Assistant automations. 

I think the above work was based on reverse engineering how the Control4 driver works to understand how to talk to the panel. Might be a useful resource if someone wanted to make a more native Homebridge implementation...

**Comment by ifeign** [comment]
@sup3rm3ga that’s the same project I linked in the initial issue. I’m glad there’s a solution, but it’s certainly more involved than the average Homebridge or even HASS plugin. I’m hoping that this knowledge can be used to create an easily installed plugin

**Comment by sup3rm3ga** [comment]
> @sup3rm3ga that’s the same project I linked in the initial issue. I’m glad there’s a solution, but it’s certainly more involved than the average Homebridge plugin or even HASS integration. I’m hoping that this knowledge can be used to create an easily installed plugin

As, sorry. I wasn't sure if Homekit users knew the above solution would work to get local control of the panel directly in HomeKit if they used Home Assistant's HomeKit Bridge functionality. Apologies!

**Comment by ifeign** [comment]
> > @sup3rm3ga that’s the same project I linked in the initial issue. I’m glad there’s a solution, but it’s certainly more involved than the average Homebridge plugin or even HASS integration. I’m hoping that this knowledge can be used to create an easily installed plugin
> 
> As, sorry. I wasn't sure if Homekit users knew the above solution would work to get local control of the panel directly in HomeKit if they used Home Assistant's HomeKit Bridge functionality. Apologies!
> 
> Edit: I can report, at least, the above functionality is very responsive from the Homekit side. Arming from my Home Favorites in iOS is instant, and the sensors update instantly.

No apology necessary, I was just clarifying. In my anecdotal experience, HASS users are generally more tech savvy than Homebridge users, so a simple all-dependencies-included solution would be nice. That said, I’m actually moving almost everything over to HASS today lol. I’m glad to hear it’s as responsive as I’d hoped.

**Comment by harryfrishberg** [comment]
Hey ifeign - I'm in a similar situation as you regarding HomeAssistant and a Qolsys IQ 2 Panel. I just don't know much about setting up the Appdaemon and MQTT side of this. Any chance you could provide a simple walkthrough for getting that 3rd party Qolsys solution working?

**Comment by ifeign** [comment]
> Hey ifeign - I'm in a similar situation as you regarding HomeAssistant and a Qolsys IQ 2 Panel. I just don't know much about setting up the Appdaemon and MQTT side of this. Any chance you could provide a simple walkthrough for getting that 3rd party Qolsys solution working?

I haven't actually set it up myself, I'm planning on doing so soon. Your best bet is to post in this thread https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/1

**Comment by ifeign** [comment]
> Hey ifeign - I'm in a similar situation as you regarding HomeAssistant and a Qolsys IQ 2 Panel. I just don't know much about setting up the Appdaemon and MQTT side of this. Any chance you could provide a simple walkthrough for getting that 3rd party Qolsys solution working?

Did you figure it out? I'm pulling my hair out trying to do this lol. I got the entities to appear in HASS, but they're not updating.
<img width="468" alt="Screen Shot 2021-07-07 at 8 36 37 PM" src="https://user-images.githubusercontent.com/32289760/124857349-c5eeeb80-df71-11eb-8212-9a3f9961a561.png">

This is another reason why a nicely packaged Homebridge plugin would be amazing - this guy seems to have some relevant info https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/102?u=ifeign

**Comment by harryfrishberg** [comment]
I'm in the same boat as you - I am following that thread with great interest, but a little daunted by the whole MQTT / HACS process. I'd GREATLY prefer if the developments on that HASS thread would somehow make their way to this plugin, allowing Chase9 or some other developer to create a more reliable homebridge plugin that can interface directly with the Qolsys hardware instead of ADC and their servers. I may take another stab at it when I'm feeling more adventurous, but until then, I am just hanging on the sidelines...

**Comment by ifeign** [comment]
After much trial and error I got it to work, and passed it into HomeKit.
Everything is super responsive! Currently trying to figure out how to
extract the z-wave network key so I can control my door lock via a z-wave
stick

**Comment by djcruz04** [comment]
I haven't read through all the comments but I did see that you needed a Qolsys IQ 2 Panel. I have 1 panel laying around and not in use if someone wanted for testing free of charge. Just take care of the shipping. Let me know.

**Comment by ifeign** [comment]
https://github.com/EHylands/homebridge-qolsys

PSA: This exists now

You won't see any z-wave devices, but the security system and the sensors are real-time
