### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#74]
**Describe the bug**
Errors in log

Node Alarm Dot Com
1.7.2-beta.7
-->

**Expected behavior**

**Screenshots**
5/17/2021, 5:53:41 AM [Security System] Logged into Alarm.com as strange4358
5/17/2021, 5:53:42 AM [Security System] UNHANDLED ERROR: TypeError: Cannot read property 'data' of undefined
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:167:69
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 5:53:47 AM [Samsung TV Series 8 65] Failed to pair! Make sure TV is online and you click "Allow" on the popup
5/17/2021, 5:53:48 AM [Samsung TV Series 8 55] Failed to pair! Make sure TV is online and you click "Allow" on the popup
5/17/2021, 5:53:48 AM [Samsung TV 40] Failed to pair! Make sure TV is online and you click "Allow" on the popup
5/17/2021, 5:56:29 AM [Security System] changePartitionState(98182855-127, 3)
5/17/2021, 5:56:37 AM [Security System] changePartitionState(98182855-127, 2)
5/17/2021, 5:56:39 AM [Security System] Updating partition Panel (98182855-127), desiredState=0, prev=2
5/17/2021, 5:57:39 AM [Security System] changePartitionState(98182855-127, 3)
5/17/2021, 5:57:43 AM [HOOBS 9033@Security System Target State] The write handler for the characteristic 'Security System Target State' on the accessory 'Panel' was slow to respond!
5/17/2021, 5:57:58 AM [Security System] TypeError: Cannot read property 'data' of undefined
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:167:69
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:04:48 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:07:57 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:11:41 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:18:40 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:25:36 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:32:49 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:37:45 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:42:12 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:45:57 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
5/17/2021, 6:53:34 AM [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
**Homebridge System (please complete the following information):**
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Additional context**

**Comment by JCallender73** [comment]
Same errors that I am receiving.

**Comment by chase9** [comment]
Please check out 1.7.2-beta.8 and see if that solved this issue.

**Comment by scottleestrange** [comment]
Beta 8 appears to have fixed it

This returns in beta 9

[5/18/21, 7:25 AM] [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:464:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

**Comment by chase9** [comment]
Interesting you say that as beta 8 was a mistake push which didn't process any lights retrieved. I wonder if ECONNECT is tied to a particular device type?

**Comment by scottleestrange** [comment]
Well first of all I have no lights.  The device types I have are 2 Key FOB, 7 Contact sensors (wired) 1 wireless motion sensor, 2 wired motion sensors (effectively one because on the same zone)

**Comment by JCallender73** [comment]
I loaded Beta 9 this morning and had same error.  Never saw a beta 8 to test.

**Comment by scottleestrange** [comment]
This happened when disarming

5/22/21, 10:26 AM] [Security System] changePartitionState(98182855-127, 3)

[5/22/21, 10:26 AM] [Security System] Error: Failed to change partition state: Error: POST https://www.alarm.com/web/api/devices/partitions/98182855-127/disarm failed: 403
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:491:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[5/22/21, 10:26 AM] [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/8220700 failed: [object Object]
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/dist/index.js:464:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)


I get errors changing all alarm states

**Comment by chase9** [comment]
Can you please test the latest beta (11) and see if this is still present?

**Comment by scottleestrange** [comment]
2 days of Beta 11 and all clear for this error.

I see this several times

8/19/2021, 5:37:03 PMNode Alarm Dot Com BridgeSecurity SystemLogged into Alarm.com<http://Alarm.com> as strange43588/19/2021, 5:46:20 PMNode Alarm Dot Com BridgeSecurity SystemERRORrefreshDevices Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=98182855-7&ids%5B%5D=98182855-12&ids%5B%5D=98182855-8&ids%5B%5D=98182855-1&ids%5B%5D=98182855-6&ids%5B%5D=98182855-10&ids%5B%5D=98182855-11&ids%5B%5D=98182855-5&ids%5B%5D=98182855-9&ids%5B%5D=98182855-3&ids%5B%5D=98182855-2&ids%5B%5D=98182855-4 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=98182855-7&ids%5B%5D=98182855-12&ids%5B%5D=98182855-8&ids%5B%5D=98182855-1&ids%5B%5D=98182855-6&ids%5B%5D=98182855-10&ids%5B%5D=98182855-11&ids%5B%5D=98182855-5&ids%5B%5D=98182855-9&ids%5B%5D=98182855-3&ids%5B%5D=98182855-2&ids%5B%5D=98182855-4 failed, reason: read ECONNRESET8/19/2021, 5:46:20 PMNode Alarm Dot Com BridgeSecurity SystemRefreshing session authentication.8/19/2021, 5:47:41 PMNode Alarm Dot Com BridgeSecurity SystemLogging into Alarm.com<http://Alarm.com> as strange4358


It seems to get an error, then immediatly logs in again and the GET succeeds.  I assume this is just simple error recovery steps for ECONNRESET (good job).  But you cannot control when they close the socket on their side.  You should see that they closed it before the 10 minutes.   So looks like nothing to worry about on your side

On Aug 19, 2021, at 2:49 PM, Chase Lau ***@***.******@***.***>> wrote:



Can you please test the latest beta (11) and see if this is still present?

**Comment by DMBlakeley** [comment]
I have found that you really can't predict problems on the server side. There are days that I might have 1 or 2 errors but other that I have 1 or 2 an hour. Found that by re-authenticating the error was cleared and that was the intent of the code change in beta.11. If error ... re-authenticate.

**Comment by scottleestrange** [comment]
Exactly, all you can do is recovery by logging back in which the plugin is clearly doing



On Aug 20, 2021, at 7:56 AM, Doug B ***@***.******@***.***>> wrote:



I have found that you really can't predict problems on the server side. There are days that I might have 1 or 2 errors but other that I have 1 or 2 an hour. Found that by re-authenticating the error was cleared and that was the intent of the code change in beta.11. If error ... re-authenticate.

**Comment by DMBlakeley** [comment]
The recovery code was one of my small contributions to 1.7.2-beta.11. Glad to hear that it is working for you as intended.

**Comment by scottleestrange** [comment]
Good job

On Aug 20, 2021, at 1:58 PM, Doug B ***@***.******@***.***>> wrote:



The recovery code was one of my small contributions to 1.7.2-beta.11. Glad to hear that it is working for you as intended.
