### ISSUE TITLE
Unhandled Error: Cannot Read Property 

### ISSUE THREAD

**Issue by anthonyb82** [node-alarm-dot-com/homebridge-node-alarm-dot-com#75]
**Describe the bug**
In an attempt to resolve intermittent issues where my panel was showing as unavailable (presumably due to the ECONN resets) I removed the plugin and reinstalled. I am now getting the error below and it will not pull any of my alarm components (panel or accessories) in to HomeKit.  I followed all steps to delete cached accessories. have reinstalled a couple of times and ensured 2FA was set up again as before. Not sure what else I could try. I have tried on both beta 4 & 7

**Error**

UNHANDLED ERROR: TypeError: Cannot read property 'data' of undefined
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:167:69
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)

**Homebridge System (please complete the following information):**
* **Node.js Version**: 14.7.0
* **NPM Version**: 7.13.0
* **Homebridge Version**: 4.41.1
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service
* **Alarm Dot Com Version**: v1.7.2-beta.4

**Comment by chase9** [comment]
Please check out 1.7.2-beta.8 and see if that solved this issue.

**Comment by anthonyb82** [comment]
I tried both beta 9 (which is what was showing for me in HB) and beta 8. Receiving the following error still: 

[5/17/2021, 10:01:10 PM] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-node-alarm-dot-com@1.7.2-beta.9
[5/17/2021, 10:02:59 PM] [Surety Security System] Logging into Alarm.com as Axxxx
[5/17/2021, 10:03:00 PM] [Surety Security System] Logged into Alarm.com as Axxxx
[5/17/2021, 10:03:00 PM] [Surety Security System] TypeError: Cannot read property 'data' of undefined
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:167:69

**Comment by anthonyb82** [comment]
Just seeing this one coming up now as well: 
Error: GET https://www.alarm.com/web/api/systems/systems/10560504 failed: [object Object]
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:465:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)

**Comment by chase9** [comment]
This one is oddly formatted but I think it’s just the ECONNECT issue.

I’ll have to investigate why you’re still seeing the data issue.

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by anthonyb82** [comment]
Yes, but not only am I seeing the errors, after uninstalling and trying to reinstall any of the versions, it’s not pulling any of the alarm equipment back in to homekit (panels, sensors, etc.).

**Comment by anthonyb82** [comment]
Interesting- I just turned debug mode on in homebridge. All my sensors/panel added in to homekit and now I’m not seeing any errors at all, including Econnect.

**Comment by chase9** [comment]
Are you using HOOBs? I’m wondering if it was caching the old plug-in or something. Glad to see it’s working better!

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by anthonyb82** [comment]
No, I’m on the Homebridge UI. Admittedly, I uninstalled and reinstalled various versions of this plugin yesterday in my attempt to get the panel to be responsive again. Something must have gotten gummed up somewhere through all that. 

Good news I am not getting the other errors in the past 24hrs with the new beta. Bad news, the econreset is still present. If I would just stop looking at my HB logs, I don’t know that I’d even notice the error though. It doesn’t seem to effect functionality. 

Anyway, thank you again sir for this plugin and for such a quick resolution on this current issue! I think this can be closed with whatever you changed in the beta. 

Anthony

**Comment by scottleestrange** [comment]
I am still seeing errors.  I am using HOOBS, but I did a connection reset to clear all cached accessories

Still the same errors

**Comment by scottleestrange** [comment]
I am getting ECONRESET ALSO

**Comment by Jotin08** [comment]
I am also getting this error. Using Homebridge UI and can't seem to get this running at all.

**Comment by harryfrishberg** [comment]
I am also encountering this new error. I tried upgrading to the newest beta, disabling/re-enabling the plugin, restarting... no luck. Still can't get it to work.

[21/08/2021, 19:48:53] [Security System] UNHANDLED ERROR: TypeError: Cannot read property 'map' of undefined
    at fetchStateForAllSystems (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:1354:34)
    at ADCPlatform.listDevices (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:305:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by chase9** [comment]
I think this error has more to do with improper authentication. I got it as well before realizing my credentials (including the 2FA code) was wrong. I made sure 2FA was enabled on my account, reconfigured my credentials, and restarted the plugin. No issues in the past week.
