### ISSUE TITLE
Ignored devices not being ignored

### ISSUE THREAD

**Issue by andywaplinger** [node-alarm-dot-com/homebridge-node-alarm-dot-com#78]
**Describe the bug**
After adding an Alarm.com device ID to the ignoredDevices list and restart Homebridge, the device still appears in my Home. This worked for other devices, but I've noticed that it has stopped working with devices that I've recently added to the list. I'm unsure of which plugin version caused this change.

**To Reproduce**
- Add device ID to ignoredDevices
- Save config
- Restart Homebridge

**Expected behavior**
The device should disappear from my Home.

**Homebridge System (please complete the following information):**
* **Node.js Version**: v14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by ifeign** [comment]
Have you tried removing the cached accessories in the Homebridge UI? Sometimes things get stufk

**Comment by andywaplinger** [comment]
I always forget about doing that - thanks for the reminder. That worked!
