### ISSUE TITLE
Can I hide the alarm panel?

### ISSUE THREAD

**Issue by danTHAman152000** [node-alarm-dot-com/homebridge-node-alarm-dot-com#80]
I like that this Homebridge plugin exposes all the window/door contact sensors to Homekit. I would like to hide the main alarm panel in Homekit, though. This is because I use Home Assistant and the similar plugin there reacts better/different when arming, but does not expose the extra contact sensors. This means I have two alarm panels in Home app, and I'd like to hide this extra one.

I see there is an option through Homebridge to hide the accessory. It didn't work. I then saw I needed to delete a cache file, and saw now Homebridge has an option to delete one specific accessory. I am successful when I do this and restart Homebridge (this duplicate alarm panel does not show up anymore), but then eventually it shows up again randomly. 

Is it even possible to hide this alarm panel? 

The difference between this Homebridge version compared to the Home Assistant one that I am using is that the icon doesn't become unresponsive when changing the alarm status. Instead, on HA, it says "arming..." continuously. It's a small issue but I prefer there being zero "no response" tiles when I open the Home app. I've noticed my Honeywell Lyric app works much better on HA than HB too, which is unrelated, but gives me more reason to move stuff to HA. 

Let me know if there is a chance to do this, or if I am barking up the wrong tree. Thanks!

**Comment by chase9** [comment]
Hi Dan,

Ignoring devices has been fixed in the beta version of the plugin. We're just working on an issue before releasing it to the stable branch. If you'd like to test, you can switch this plugin to the beta branch within home bridge.

**Comment by danTHAman152000** [comment]
Thank you for the quick reply. I currently have: homebridge-node-alarm-dot-com v1.7.2-beta.4 installed. If this is the latest beta, then I will wait for a stable update.

And to clarify, currently on this beta, I get the alarm panel to be hidden but then randomly comes back for me.

**Comment by chase9** [comment]
I believe we’re up to beta.10 now, and ignoring devices was fixed after the version you’re on. Try giving it an update and let me know if your problems fixed :)

Chase

Please excuse any grammatical errors as this was sent from my iPhone.
