### ISSUE TITLE
HOOBS 4

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#87]
Maybe not  really a bug - I installed HOOBS 4 (upgrade) and I can no longer see beyond Beta 4 on the UI...any thoughts on how to fix?

**Comment by DMBlakeley** [comment]
I have no experience with HOOBS but found the following [instructions](https://github.com/hoobs-org/HOOBS/issues/186) for installing plugins manually. To install the beta you would use:

`npm install homebridge-node-alarm-dot-com@1.7.2-beta.11`

**Comment by chase9** [comment]
I will investigate why HOOBs doesn't have the latest beta available, but I do understand that they use some sort of plugin whitelist. In the meantime, DMBlakeley pointed you to some great instructions.

**Comment by chase9** [comment]
For future reference, the HOOBS repo should now contain the latest beta version. One of the authors of HOOBS let me know that beta versions don't trigger HOOBS updating their repos, so it's a manual process on their end.

**Comment by scottleestrange** [comment]
Thank you all for the help.

**Comment by scottleestrange** [comment]
I can see all now.  With hoobs 3 I could also.  Again thanks
