### ISSUE TITLE
Lights dont function properly

### ISSUE THREAD

**Issue by Stugatza** [node-alarm-dot-com/homebridge-node-alarm-dot-com#90]
In 1.8 i can turn a light off and never get it back on.

[11/17/2021, 14:21:43] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/94428553-1201/turnOn failed: 423
    at post (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:489:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at authenticatedPost (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:433:17)
    at ADCPlatform.changeLight (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:909:5)

**Comment by Stugatza** [comment]
anyone else experiencing?  still have this after the 1.11 patch installed via terminal.  all other functions seem solid.  can turn lights off, but cannot turn any on.

**Comment by Stugatza** [comment]
Also, prior to the reset issues if the code was modified with brightness=true it would get the lights to turn on consistently.

**Comment by mwderner** [comment]
I'm also having this problem.  I can turn off the light but it will not turn it back on

**Comment by Stugatza** [comment]
Any thoughts on the issue?

**Comment by Prose78** [comment]
I'm also experiencing this issue with 1 of my 2 lights, which I thought was strange.  Everything else works solid so far.

[1/6/2022, 9:22:53 PM] [Security System] Updating light Master Light (96029166-1207), state=false, prev=true
[1/6/2022, 9:25:59 PM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights//turnOn failed: 423
    at post (/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:489:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at authenticatedPost (/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:433:17)
    at ADCPlatform.changeLight (/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:909:5)

**Comment by weissk93** [comment]
I am having the same issue. Has anyone had success at all?

**Comment by ChrArk** [comment]
Same issue here i can turn all  lights off but only can turn only one light back on. Any solution to this issue?

**Comment by ngori** [comment]
For those having issues with lights I have two questions:  1) What type of lights are you trying to control?  Z-wave devices directly communicating with your panel or a cloud to cloud integration (i.e., Lutron).   2) Are the devices on/off switches or dimmers?

I have a mix of both in my setup but primarily Lutron devices which are natively HomeKit supported (I exclude the ADC versions of my Lutron devices to not create dupes). I do have one z-wave on/off device directly communicating with my panel but haven't experienced any issues with it.  Hence, I'm wondering if this is a dimmer related problem.  I remember previous issues with the dimmer implementation.

**Comment by Stugatza** [comment]
GE zwave to Qolsys without dimmer

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChrArk** [comment]
Zwave to ADT panel no dimmers connected to alarm.com one light works all others don’t but all the same switches

**Comment by kwallac** [comment]
Same issue here. Alarm.com. All but one light works. The one that fails can be turned off but not turned on

Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/94329577-1211/turnOn failed: 423
    at post (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:489:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at authenticatedPost (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:433:17)
    at ADCPlatform.changeLight (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:909:5)
    
    Any ideas appreciated

**Comment by ngori** [comment]
@kwallac has submitted a PR to correct this issue on the node-alarm-com repo (the interface module for this plugin).  I can't test this PR but if some of the folks having issues could test and report back we can hopefully merge his fix.  

https://github.com/node-alarm-dot-com/node-alarm-dot-com/pull/23

**Comment by Stugatza** [comment]
Sill question, but what is the best way to get the latest pkg installed

On Feb 8, 2022, at 9:36 AM, ngori ***@***.******@***.***>> wrote:



@kwallac<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkwallac&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rx96hQW9Qbtq754FDaxu6MpaAO%2FT6wY5iHl6gQJnmuc%3D&reserved=0> has submitted a PR to correct this issue on the node-alarm-com repo (the interface module for this plugin). I can't test this PR but if some of the folks having issues could test and report back we can hopefully merge his fix.

node-alarm-dot-com/node-alarm-dot-com#23<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-alarm-dot-com%2Fnode-alarm-dot-com%2Fpull%2F23&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HHeBTdKEUcDPmKpIFz1hChx%2BeV0ac7sU3640LTfD6%2Bc%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-alarm-dot-com%2Fhomebridge-node-alarm-dot-com%2Fissues%2F90%23issuecomment-1032677288&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zyuBghijvOHAqi%2BlZMuRZK1fUE2MDC88wruBkZM9c3Y%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOCFBWFCXY4K5AQLLOW3SF3U2ES5DANCNFSM5IHZY2LQ&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ERN5VhD%2BoKmlWeQ4viZXsuXiKmZO23IcE3uMxFDLoG8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kp788DtpzkMhVCeaZWOEaQHCb%2BNs9jZqHsLDvUz13DM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C731cd1591a0046a1539708d9eb10543f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799277626788507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QQfRhJ9VESacohssATR%2BuYvhc%2Fsxe2CTU3wcAZmbcnM%3D&reserved=0>.

**Comment by kwallac** [comment]
The fix requires an extra parameter (isDimmer) to be passed to the node-alarm-dot-com method. I have a PR for the homebridge-node-alarm-dot-com plugin that does and have tested end-to-end and all works. Not sure how to manage the dependency though as it assumes the https://github.com/node-alarm-dot-com/node-alarm-dot-com/pull/23 PR has been accepted as version 1.1.11

**Comment by ngori** [comment]
@kwallac I only see a PR for the node-alarm-dot-com interface nothing for home-bridge-node-alarm-dot-com?

**Comment by kwallac** [comment]
Hi @ngori I went ahead and created https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/pull/93
but as mentioned requires an update to the node-alarm-dot-com library per https://github.com/node-alarm-dot-com/node-alarm-dot-com/pull/23

I've tested that it works with both types of lights (dimmable and non-dimmable)

**Comment by Stugatza** [comment]
Can this be merged into the homebridge repo and made avail as an update?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chase9** [comment]
@kwallac @ngori Thank you both so much for your help. As you can tell, I've been absent due to personal reasons so it was so great to see a pull request! This has been merged into 1.8.1-beta.0. Please test and let me know if you run into bugs.

**Comment by Stugatza** [comment]
The fix is performing great!  Appreciate everyone’s hard work on this one.

On Feb 9, 2022, at 2:09 PM, Chase Lau ***@***.******@***.***>> wrote:



@kwallac<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkwallac&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QXN2dAczQ7qZd7qTaR6VkR6GnZ8z%2BXU9mFXGJo3xqqI%3D&reserved=0> @ngori<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fngori&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Nc6jhdwSq1KAHOLoDMZ%2Bc1vUSU7oZU98IYPM6Gv5geI%3D&reserved=0> Thank you both so much for your help. As you can tell, I've been absent due to personal reasons so it was so great to see a pull request! This has been merged into 1.8.1-beta.0. Please test and let me know if you run into bugs.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-alarm-dot-com%2Fhomebridge-node-alarm-dot-com%2Fissues%2F90%23issuecomment-1034101583&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k0pz2pASV%2FgC%2FkwFzRBbmXL%2FrPV1p1vFSH8Rew%2BefX4%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOCFBWDMAEET222AQKEGNDLU2K3XVANCNFSM5IHZY2LQ&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xvk06ruQKAIQKgItXmSKtjcS1CYNhWqFloof2x%2FJ%2BCs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y2MWvWtpOW0S1p3N%2B0pgEKhWz6qTEtHCy5b4ad%2BEkK8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C039b25bccd3141c0665808d9ebffbd01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800305892966203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AVFVfKCRshn35sjbIqLNPwHWljsqFqM4i%2FhKC91GDd0%3D&reserved=0>.

**Comment by ChrArk** [comment]
Can someone please guide me through on how to implement the fix? I'm a complete newbie. I would highly appreciate that! I can reimburse you for your time! Thank you

**Comment by ngori** [comment]
@ChrArk  If you are using Homebridge UI interface you can click on the wrench, then "Install Previous Version", then from the version list the beta with the change implemented will be at the top.

<img width="295" alt="beta" src="https://user-images.githubusercontent.com/29135202/153609552-e44c98d7-98ba-402e-9906-cef192d1acaa.png">

**Comment by ChrArk** [comment]
Thank you so much for explaining it!!! I’ll give that a try tonight. 

Kind regards / Mit freundlichen Grüßen

Christian Arkenberg

**Comment by ChrArk** [comment]
@ngori Thank you again everything works fine now! Thank you to everyone who made all this possible and shared it with the public! One more question I ordered a Z-shield for the raspberry PI but it seem like I don't even need that? Can someone explain why and when its needed and when not? I'm assuming it functions similar to a hub which we have the IQ pad for correct?

**Comment by ngori** [comment]
I'm not familiar with the z-Shield but it looks like a Zigbee interface for Home Assistant. The IQ panel has only limited Zigbee functionality for use with the image sensors. It doesn't support other devices (lights, switches, outlets). The IQ panels do have decent z-wave functionality. So it just depends on what you are trying to do if you need the Z-Shield. 




> @ngori Thank you again everything works fine now! Thank you to everyone who made all this possible and shared it with the public! One more question I ordered a Z-shield for the raspberry PI but it seem like I don't even need that? Can someone explain why and when its needed and when not? I'm assuming it functions similar to a hub which we have the IQ pad for correct?

**Comment by Mikelawry214** [comment]
Hello. Are people in the Hoobs system able to update to this beta program. I am having the same problems with my lights.
