### ISSUE TITLE
I have loglevel set to 0 but I get notifications every 10 minutes when the server is logged into. Can I get rid of this log too?

### ISSUE THREAD

**Issue by danTHAman152000** [node-alarm-dot-com/homebridge-node-alarm-dot-com#92]
I thought with loglevel set to 0 that I would not get an entry for logging in, but it keeps showing up. Can I get rid of this? I don't need to know every 10 minutes. Thanks!

**Comment by chase9** [comment]
I just spent a while looking into this and realized that logging is all wrong. We've switched to using homebridge logging for the most part, but that doesn't respect any logging levels besides those which have to be set using a separate homekit app. I think this isn't ideal.

I like to use the integrated solution but at this point I think it's probably easiest to wrap every logging call in a check to look at the log level and then only proceed if the level is the same or higher.

**Comment by chase9** [comment]
Hi @danTHAman152000, please checkout 1.8.1-beta.1 and let me know if your issue is fixed. Thanks!
