### ISSUE TITLE
Motion sensor and glass break inverted

### ISSUE THREAD

**Issue by cbusillo** [node-alarm-dot-com/homebridge-node-alarm-dot-com#97]
Hi, my motion and glass break sensors are inverted in HB and HK.  Both show as activated with no motion or glass break.  Is there a way to invert the sensor, or is there a bug in my setup?  I have everything fully updated.  What information should I provide to help figure this out?  Thank you!

**Comment by ngori** [comment]
@cbusillo I'm by no means an expert but this sounds like a setup bug.  I believe both sensors types are normally setup as NC at the panel and then fault when opened (That is is how my setup works at least which is pretty vanilla).  My setup is a Qolsys IQ setup and that is the default setup when you enroll devices.

**Comment by cbusillo** [comment]
My glass break in Home Bridge shows open. The motion detector occupancy detected shows 0 when I am in the building and 1 when I am away.  I can't think of anythinng I have changed that would do this.

**Comment by dppeak** [comment]
@cbusillo & @ngori This is not a set up issue for the Glass Break sensors.  This is the way that Glass Break sensors report from Alarm.com.  I mentioned this [here](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/18#issuecomment-950003451) that they remain Open until disrupted.  It would be nice if this plugin was updated to account for this quirk.

**Comment by cbusillo** [comment]
> @cbusillo & @ngori This is not a set up issue for the Glass Break sensors. This is the way that Glass Break sensors report from Alarm.com. I mentioned this [here](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/18#issuecomment-950003451) that they remain Open until disrupted. It would be nice if this plugin was updated to account for this quirk.

Thank you.  I did not notice the other issue.  I tried to invert the code, but I’m not sure I did it right in the environment.  If its a common thing it would be nice to have a setting to invert specific sensors.

**Comment by chase9** [comment]
Hi all, glass break and heat sensor inversion should be fixed in [83e8d44](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/commit/83e8d44ac5c33350a8879dd6fe511a30f52586c9). I'm not seeing motion sensors inverted on my side. Can anyone still confirm this is happening with the latest version of the plugin?

**Comment by cbusillo** [comment]
No longer using alarm.com. Sorry!

**Comment by chase9** [comment]
No problem, thanks for the follow up! I'll close this one.
