### ISSUE TITLE
Can get alarm.com bridge running on HOOBS but can't add to Apple Home

### ISSUE THREAD

**Issue by docgould3** [node-alarm-dot-com/homebridge-node-alarm-dot-com#99]
disclosure - I am a Homebridge newbie, a programming novice, and this is my first Github post ... 

Good afternoon. I seem to have the alarm.com bridge installed and running on my HOOBS device. But every time I try to add it to Apple Home, it says "accessory not found." I've tried restarting the bridge, reinstalling the bridge, restarting Home, etc. Any suggestions?

Thanks for any help and/or suggestions.

**Comment by ngori** [comment]
Hi @docgould3 

I don't have HOOBS experience but how are you trying to add "it" to Apple Home. I run Homebridge on a raspberry pi. I installed Homebridge first via the QR code and all the associated accessories from plugins installed and configured on Homebridge appear in my HomeKit setup. The appear in a default room and not on the main page with the favorites. I now run my alarm.com plug-in as a child bridge for other reason but I don't think that's what you are doing. 


> disclosure - I am a Homebridge newbie, a programming novice, and this is my first Github post ... 
> 
> 
> 
> Good afternoon. I seem to have the alarm.com bridge installed and running on my HOOBS device. But every time I try to add it to Apple Home, it says "accessory not found." I've tried restarting the bridge, reinstalling the bridge, restarting Home, etc. Any suggestions?
> 
> 
> 
> Thanks for any help and/or suggestions.

**Comment by docgould3** [comment]
I have HOOBS on a raspberry pi. I add my bridges to HomeKit by going to “add an accessory” and then scan the QR code on HOOBS. Apple Home then tries to add the bridge as an accessory and returns the above error. I am able to add Ring and Sonos via HOOBS so think this is specific to the alarm.com bridge. jgOn Sep 2, 2022, at 3:28 PM, ngori ***@***.***> wrote:﻿
Hi @docgould3
I don't have HOOBS experience but how are you trying to add "it" to Apple Home. I run Homebridge on a raspberry pi. I installed Homebridge first via the QR code and all the associated accessories from plugins installed and configured on Homebridge appear in my HomeKit setup. The appear in a default room and not on the main page with the favorites. I now run my alarm.com plug-in as a child bridge for other reason but I don't think that's what you are doing.

disclosure - I am a Homebridge newbie, a programming novice, and this is my first Github post ...
Good afternoon. I seem to have the alarm.com bridge installed and running on my HOOBS device. But every time I try to add it to Apple Home, it says "accessory not found." I've tried restarting the bridge, reinstalling the bridge, restarting Home, etc. Any suggestions?
Thanks for any help and/or suggestions.

**Comment by ngori** [comment]
So, I've never used HOOBS but looked at the documentation and it does look like it is adding each accessory as its own bridge which is a bit different than a stock homebridge install using something like homebridge UI on top. What we would really need to see is the log output from HOOBS to see what specifically is failing for the alarm-dot-com plug-in

**Comment by chase9** [comment]
I agree that I'm not sure this is an issue with the plugin, but I also have no experience with HOOBS. If you would like us to look into this more, please post your sanitized logs.
